In [1]:
import pandas as pd
import numpy as np 
import copy
from matplotlib import pyplot as plt
import seaborn as sns
from collections import *
import datetime

In [2]:
data=pd.read_csv(r"C:\Users\Mark 1\Desktop\Lockdown\data\Covid-19\106\case_time_series.csv")
data.head()

,Date,Daily Confirmed,Total Confirmed,Daily Recovered,Total Recovered,Daily Deceased,Total Deceased
0,30 January,1,1,0,0,0,0
1,31 January,0,1,0,0,0,0
2,01 February,0,1,0,0,0,0
3,02 February,1,2,0,0,0,0
4,03 February,1,3,0,0,0,0

In [3]:
data_daily=data[53:]
data_daily.reset_index(drop=True,inplace=True)
data_daily.head()

,Date,Daily Confirmed,Total Confirmed,Daily Recovered,Total Recovered,Daily Deceased,Total Deceased
0,23 March,94,497,2,25,2,9
1,24 March,74,571,15,40,1,10
2,25 March,86,657,3,43,1,11
3,26 March,73,730,7,50,5,16
4,27 March,153,883,25,75,3,19

In [4]:
data_daily.tail()

,Date,Daily Confirmed,Total Confirmed,Daily Recovered,Total Recovered,Daily Deceased,Total Deceased
203,12 October,54262,7173571,78365,6224767,710,109308
204,13 October,63717,7237288,74079,6298846,727,110035
205,14 October,67811,7305099,81582,6380428,690,110725
206,15 October,63441,7368540,70792,6451220,882,111607
207,16 October,62302,7430842,70568,6521788,840,112447

In [5]:
colls=list(data_daily.columns)
colls

['Date',
 'Daily Confirmed',
 'Total Confirmed',
 'Daily Recovered',
 'Total Recovered',
 'Daily Deceased',
 'Total Deceased']

In [6]:
data_daily.dtypes

Date               object
Daily Confirmed     int64
Total Confirmed     int64
Daily Recovered     int64
Total Recovered     int64
Daily Deceased      int64
Total Deceased      int64
dtype: object

In [7]:
data_daily[data_daily.duplicated()]

Empty DataFrame
Columns: [Date, Daily Confirmed, Total Confirmed, Daily Recovered, Total Recovered, Daily Deceased, Total Deceased]
Index: []

In [8]:
data_daily['Date'] = data_daily['Date'].astype('str')

<ipython-input-8-b893dc2657ae>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily['Date'] = data_daily['Date'].astype('str')

In [9]:
for i in range(0,9):
    data_daily["Date"][i]=data_daily["Date"][i].strip(" March")
for i in range(0,9):
    data_daily["Date"][i]="2020-03-"+data_daily["Date"][i]

<ipython-input-9-5d3a9c25c0f3>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]=data_daily["Date"][i].strip(" March")
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3343: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
<ipython-input-9-5d3a9c25c0f3>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]="2020-03-"+data_daily["Date"][i]

In [10]:
for i in range(9,39):
    data_daily["Date"][i]=data_daily["Date"][i].strip(" April")
for i in range(9,39):
    data_daily["Date"][i]="2020-04-"+data_daily["Date"][i]

<ipython-input-10-e708bf0423ae>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]=data_daily["Date"][i].strip(" April")
<ipython-input-10-e708bf0423ae>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]="2020-04-"+data_daily["Date"][i]

In [11]:
for i in range(39,70):
    data_daily["Date"][i]=data_daily["Date"][i].strip(" May")
for i in range(39,70):
    data_daily["Date"][i]="2020-05-"+data_daily["Date"][i]

<ipython-input-11-3a877ff4aac3>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]=data_daily["Date"][i].strip(" May")
<ipython-input-11-3a877ff4aac3>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]="2020-05-"+data_daily["Date"][i]

In [12]:
for i in range(70,100):
    data_daily["Date"][i]=data_daily["Date"][i].strip(" June")
for i in range(70,100):
    data_daily["Date"][i]="2020-06-"+data_daily["Date"][i]

<ipython-input-12-7dad98128838>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]=data_daily["Date"][i].strip(" June")
<ipython-input-12-7dad98128838>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]="2020-06-"+data_daily["Date"][i]

In [13]:
for i in range(100,131):
    data_daily["Date"][i]=data_daily["Date"][i].strip(" July")
for i in range(100,131):
    data_daily["Date"][i]="2020-07-"+data_daily["Date"][i]

<ipython-input-13-8446ec7a3871>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]=data_daily["Date"][i].strip(" July")
<ipython-input-13-8446ec7a3871>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]="2020-07-"+data_daily["Date"][i]

In [14]:

for i in range(131,162):
    data_daily["Date"][i]=data_daily["Date"][i].strip(" August")
for i in range(131,162):
    data_daily["Date"][i]="2020-08-"+data_daily["Date"][i]

<ipython-input-14-8378c44cbf95>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]=data_daily["Date"][i].strip(" August")
<ipython-input-14-8378c44cbf95>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]="2020-08-"+data_daily["Date"][i]

In [15]:

for i in range(162,192):
    data_daily["Date"][i]=data_daily["Date"][i].strip(" September")
for i in range(162,192):
    data_daily["Date"][i]="2020-09-"+data_daily["Date"][i]

<ipython-input-15-35b96d5b39bd>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]=data_daily["Date"][i].strip(" September")
<ipython-input-15-35b96d5b39bd>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]="2020-09-"+data_daily["Date"][i]

In [16]:
for i in range(192,len(data_daily)):
    data_daily["Date"][i]=data_daily["Date"][i].strip(" October")
for i in range(192,len(data_daily)):
    data_daily["Date"][i]="2020-10-"+data_daily["Date"][i]

<ipython-input-16-4fd5b8dff3d9>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]=data_daily["Date"][i].strip(" October")
<ipython-input-16-4fd5b8dff3d9>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]="2020-10-"+data_daily["Date"][i]

In [17]:
#data_daily['Date'][162]=data_daily['Date'][162].strip("2020-09-2020-08-01")
#data_daily['Date'][162]="2020-09-01"

In [18]:
data_daily["Date"]=data_daily["Date"].astype('datetime64[ns]')

<ipython-input-18-523dc667f175>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"]=data_daily["Date"].astype('datetime64[ns]')

In [19]:
data_daily.dtypes

Date               datetime64[ns]
Daily Confirmed             int64
Total Confirmed             int64
Daily Recovered             int64
Total Recovered             int64
Daily Deceased              int64
Total Deceased              int64
dtype: object

In [20]:
data_daily_ratio_with_two_precision=data_daily.copy()

In [21]:
new_cols=["Daily_Confirmed_Ratio","Total_Confirmed_Ratio","Daily_Recovered_Ratio","Total_Recovered_Ratio","Daily_Deceased_Ratio","Total_Deceased_Ratio"]
existing_cols=list(data_daily_ratio_with_two_precision.columns)
existing_cols.pop(0)
existing_cols
for i,j in zip(new_cols,existing_cols):
    data_daily_ratio_with_two_precision[i]=list(range(len(data_daily_ratio_with_two_precision)))
    data_daily_ratio_with_two_precision[i][0]=1
    tmp=[]
    tmp.append(data_daily_ratio_with_two_precision[i][0])
    for k in range(0,len(data_daily_ratio_with_two_precision)-1):
        tmp.append(round(data_daily_ratio_with_two_precision[j][k+1]/data_daily_ratio_with_two_precision[j][k],2))
    data_daily_ratio_with_two_precision[i]=tmp
data_daily_ratio_with_two_precision.head()

<ipython-input-21-f5761363647c>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily_ratio_with_two_precision[i][0]=1

,Date,Daily Confirmed,Total Confirmed,Daily Recovered,Total Recovered,Daily Deceased,Total Deceased,Daily_Confirmed_Ratio,Total_Confirmed_Ratio,Daily_Recovered_Ratio,Total_Recovered_Ratio,Daily_Deceased_Ratio,Total_Deceased_Ratio
0,2020-03-23,94,497,2,25,2,9,1.00,1.00,1.00,1.00,1.0,1.00
1,2020-03-24,74,571,15,40,1,10,0.79,1.15,7.50,1.60,0.5,1.11
2,2020-03-25,86,657,3,43,1,11,1.16,1.15,0.20,1.08,1.0,1.10
3,2020-03-26,73,730,7,50,5,16,0.85,1.11,2.33,1.16,5.0,1.45
4,2020-03-27,153,883,25,75,3,19,2.10,1.21,3.57,1.50,0.6,1.19

In [22]:
data_daily_ratio=data_daily.copy()

In [23]:
new_cols=["Daily_Confirmed_Ratio","Total_Confirmed_Ratio","Daily_Recovered_Ratio","Total_Recovered_Ratio","Daily_Deceased_Ratio","Total_Deceased_Ratio"]
existing_cols=list(data_daily_ratio.columns)
existing_cols.pop(0)
existing_cols
for i,j in zip(new_cols,existing_cols):
    data_daily_ratio[i]=list(range(len(data_daily_ratio)))
    data_daily_ratio[i][0]=1
    tmp=[]
    tmp.append(data_daily_ratio[i][0])
    for k in range(0,len(data_daily_ratio)-1):
        tmp.append(data_daily_ratio[j][k+1]/data_daily_ratio[j][k])
    data_daily_ratio[i]=tmp
data_daily_ratio.head()

<ipython-input-23-d765217f50de>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily_ratio[i][0]=1

,Date,Daily Confirmed,Total Confirmed,Daily Recovered,Total Recovered,Daily Deceased,Total Deceased,Daily_Confirmed_Ratio,Total_Confirmed_Ratio,Daily_Recovered_Ratio,Total_Recovered_Ratio,Daily_Deceased_Ratio,Total_Deceased_Ratio
0,2020-03-23,94,497,2,25,2,9,1.000000,1.000000,1.000000,1.000000,1.0,1.000000
1,2020-03-24,74,571,15,40,1,10,0.787234,1.148893,7.500000,1.600000,0.5,1.111111
2,2020-03-25,86,657,3,43,1,11,1.162162,1.150613,0.200000,1.075000,1.0,1.100000
3,2020-03-26,73,730,7,50,5,16,0.848837,1.111111,2.333333,1.162791,5.0,1.454545
4,2020-03-27,153,883,25,75,3,19,2.095890,1.209589,3.571429,1.500000,0.6,1.187500

In [24]:
strt_cnt=1
end_cnt=8
strt_lst=[]
end_lst=[]
strt_lst.append(strt_cnt)
end_lst.append(end_cnt)
while(end_cnt<=len(data_daily_ratio)):
        strt_cnt+=1
        strt_lst.append(strt_cnt)
        end_cnt+=1
        end_lst.append(end_cnt)
if(end_lst[len(end_lst)-1]>=len(data_daily_ratio)):
    end_lst.pop(len(end_lst)-1)
strt_lst.pop(len(strt_lst)-1)
#print(strt_lst)
#print(end_lst)
#print(len(strt_lst)==len(end_lst))

for st,en in zip(strt_lst,end_lst):

    dcr=data_daily_ratio.iloc[st:en,11:12]
    dcr.reset_index(inplace = True, drop = True)
    dc=data_daily_ratio.iloc[st:en,5:6]
    dc.reset_index(inplace = True, drop = True)



    next_day_confirmedd_case_count_mean_based=dcr.mean()[0]*dc.mean()[0]

    next_day_confirmedd_case_count_max_based=max(dcr["Daily_Deceased_Ratio"])*max(dc["Daily Deceased"])


    next_day_confirmedd_case_count_mean_max_based=dcr.mean()[0]*max(dc["Daily Deceased"])


    next_day_confirmedd_case_count_max_mean_based=max(dcr["Daily_Deceased_Ratio"])*dc.mean()[0]


    next_day_confirmedd_case_count_mean_last_based=dcr.mean()[0]*dc["Daily Deceased"][len(dc)-1]


    next_day_confirmedd_case_count_last_mean_based=dcr["Daily_Deceased_Ratio"][len(dcr)-1]*dc.mean()[0]


    next_day_confirmedd_case_count_last_based=dcr["Daily_Deceased_Ratio"][len(dcr)-1]*dc["Daily Deceased"][len(dc)-1]


    next_day_confirmedd_case_count_middle_based=dcr["Daily_Deceased_Ratio"][3]*dc["Daily Deceased"][3]


    pred_val=[]
    pred_val.append(np.round(next_day_confirmedd_case_count_mean_based))
    pred_val.append(np.round(next_day_confirmedd_case_count_max_based))
    pred_val.append(np.round(next_day_confirmedd_case_count_mean_max_based))
    pred_val.append(np.round(next_day_confirmedd_case_count_max_mean_based))
    pred_val.append(np.round(next_day_confirmedd_case_count_mean_last_based))
    pred_val.append(np.round(next_day_confirmedd_case_count_last_mean_based))
    pred_val.append(np.round(next_day_confirmedd_case_count_last_based))
    pred_val.append(np.round(next_day_confirmedd_case_count_middle_based))

    if(en<len(data_daily_ratio)):
        pred_dict={"date":data_daily_ratio["Date"][en-1]+datetime.timedelta(hours=24),"original_val":data_daily_ratio["Daily Deceased"][en],"mean_based":pred_val[0],"max_based":pred_val[1],"mean_max_based":pred_val[2],"max_mean_based":pred_val[3],"mean_last_based":pred_val[4],"last_mean_based":pred_val[5],"last_based":pred_val[6],"middle_based":pred_val[7]}
    else:
        pred_dict={"date":data_daily_ratio["Date"][en-1]+datetime.timedelta(hours=24),"original_val":0,"mean_based":pred_val[0],"max_based":pred_val[1],"mean_max_based":pred_val[2],"max_mean_based":pred_val[3],"mean_last_based":pred_val[4],"last_mean_based":pred_val[5],"last_based":pred_val[6],"middle_based":pred_val[7]}
   
    pred_df=pd.DataFrame(pred_dict, index=[0])
    
    

d=pd.read_excel(r"C:\Users\Mark 1\damprd_df_strd.xlsx")
d=pd.concat([d,pred_df])
d.reset_index(drop=True,inplace=True)
d['original_val'][len(d)-2]=data_daily_ratio['Daily Deceased'][len(data_daily_ratio)-1]
d.to_excel("damprd_df_strd.xlsx")

<ipython-input-24-e3fe42adcff5>:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d['original_val'][len(d)-2]=data_daily_ratio['Daily Deceased'][len(data_daily_ratio)-1]

In [25]:
dc=pd.read_excel(r"C:/Users/Mark 1/damprd_df_strd.xlsx")
dc = dc.loc[:, ~dc.columns.str.contains('^Unnamed')]
dc.tail()

,date,original_val,mean_based,max_based,mean_max_based,max_mean_based,mean_last_based,last_mean_based,last_based,middle_based
196,2020-10-13,723,874,1106,962,1005,690,785,620,892
197,2020-10-14,690,824,985,926,877,692,877,736,913
198,2020-10-15,882,785,990,924,842,659,781,655,718
199,2020-10-16,840,806,1188,924,1036,877,1036,1127,620
200,2020-10-17,0,792,1177,915,1020,834,760,800,744

In [26]:
dce=dc.copy()

In [27]:
strt_cnt=1
end_cnt=8
strt_lst=[]
end_lst=[]
strt_lst.append(strt_cnt)
end_lst.append(end_cnt)
while(end_cnt<=len(data_daily_ratio)):
        strt_cnt+=1
        strt_lst.append(strt_cnt)
        end_cnt+=1
        end_lst.append(end_cnt)
if(end_lst[len(end_lst)-1]>=len(data_daily_ratio)):
    end_lst.pop(len(end_lst)-1)
strt_lst.pop(len(strt_lst)-1)
#print(strt_lst)
#print(end_lst)
#print(len(strt_lst)==len(end_lst))
#print(len(strt_lst))
#print(len(end_lst))

202

In [28]:
colls=list(dc.columns)
colls.pop(0)
colls.pop(0)
collss=["mb","mxb","memb","mxmb","mlb","lmb","lb","mdb"]
for i in collss:
    dce[i]=pd.Series(range(1,len(dce)+1))
colls

['mean_based',
 'max_based',
 'mean_max_based',
 'max_mean_based',
 'mean_last_based',
 'last_mean_based',
 'last_based',
 'middle_based']

In [29]:
for i,j in zip(colls,collss):
    for k in range(len(dce)):
        dce[j][k]=dce["original_val"][k]-dce[i][k]
dce

<ipython-input-29-e3d4143616d2>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dce[j][k]=dce["original_val"][k]-dce[i][k]

,date,original_val,mean_based,max_based,mean_max_based,max_mean_based,mean_last_based,last_mean_based,last_based,middle_based,mb,mxb,memb,mxmb,mlb,lmb,lb,mdb
0,2020-03-31,6,9,70,28,23,28,21,65,2,-3,-64,-22,-17,-22,-15,-59,4
1,2020-04-01,6,11,70,28,26,12,2,3,8,-5,-64,-22,-20,-6,4,3,-2
2,2020-04-02,16,12,70,28,30,12,6,6,2,4,-54,-12,-14,4,10,10,14
3,2020-04-03,14,13,75,27,35,27,20,43,65,1,-61,-13,-21,-13,-6,-29,-51
4,2020-04-04,13,16,75,27,43,24,8,12,3,-3,-62,-14,-30,-11,5,1,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,2020-10-13,723,874,1106,962,1005,690,785,620,892,-151,-383,-239,-282,33,-62,103,-169
197,2020-10-14,690,824,985,926,877,692,877,736,913,-134,-295,-236,-187,-2,-187,-46,-223
198,2020-10-15,882,785,990,924,842,659,781,655,718,97,-108,-42,40,223,101,227,164
199,2020-10-16,840,806,1188,924,1036,877,1036,1127,620,34,-348,-84,-196,-37,-196,-287,220
200,2020-10-17,0,792,1177,915,1020,834,760,800,744,-792,-1177,-915,-1020,-834,-760,-800,-744

In [30]:
dce.to_excel("damerrprd_df_strd.xlsx")
dce=pd.read_excel(r"C:\Users\Mark 1\damerrprd_df_strd.xlsx")
dce = dce.loc[:, ~dce.columns.str.contains('^Unnamed')]
dce.to_excel("damerrprd_df_strd.xlsx")

In [31]:
edf=dce.iloc[0:len(dce),10:]
edf

      mb   mxb  memb  mxmb  mlb  lmb   lb  mdb
0     -3   -64   -22   -17  -22  -15  -59    4
1     -5   -64   -22   -20   -6    4    3   -2
2      4   -54   -12   -14    4   10   10   14
3      1   -61   -13   -21  -13   -6  -29  -51
4     -3   -62   -14   -30  -11    5    1   10
..   ...   ...   ...   ...  ...  ...  ...  ...
196 -151  -383  -239  -282   33  -62  103 -169
197 -134  -295  -236  -187   -2 -187  -46 -223
198   97  -108   -42    40  223  101  227  164
199   34  -348   -84  -196  -37 -196 -287  220
200 -792 -1177  -915 -1020 -834 -760 -800 -744

[201 rows x 8 columns]

In [32]:

for j,k in zip(range(len(edf)),range(len(dce)-1)):
    
    a=list(edf.loc[j])
    pos=[]
    neg=[]
    for i in a:
        if(i>=0):
            pos.append(i)
        else:
            neg.append(i)
    if(len(pos)):
        ps=min(pos)
        psi=a.index(ps)
        psc=list(edf.columns)[psi]
    if(len(neg)):
        ng=max(neg)
        ngi=a.index(ng)
        ngc=list(edf.columns)[ngi]
    
    
    print("for date: "+str(dce["date"][k]).strip("00:00:00")+" the lowest positve error was by the method: "+psc+" and the highest negative error by the method: "+ngc)

for date: 2020-03-31  the lowest positve error was by the method: mdb and the highest negative error by the method: mb
for date: 2020-04-01  the lowest positve error was by the method: lb and the highest negative error by the method: mdb
for date: 2020-04-02  the lowest positve error was by the method: mb and the highest negative error by the method: memb
for date: 2020-04-03  the lowest positve error was by the method: mb and the highest negative error by the method: lmb
for date: 2020-04-04  the lowest positve error was by the method: lb and the highest negative error by the method: mb
for date: 2020-04-05  the lowest positve error was by the method: mlb and the highest negative error by the method: memb
for date: 2020-04-06  the lowest positve error was by the method: mlb and the highest negative error by the method: lmb
for date: 2020-04-07  the lowest positve error was by the method: memb and the highest negative error by the method: mxmb
for date: 2020-04-08  the lowest positve error was by the method: mdb and the highest negative error by the method: mb
for date: 2020-04-09  the lowest positve error was by the method: mdb and the highest negative error by the method: mxmb
for date: 2020-04-10  the lowest positve error was by the method: mdb and the highest negative error by the method: mb
for date: 2020-04-11  the lowest positve error was by the method: mb and the highest negative error by the method: mdb
for date: 2020-04-12  the lowest positve error was by the method: mb and the highest negative error by the method: lmb
for date: 2020-04-13  the lowest positve error was by the method: mb and the highest negative error by the method: lmb
for date: 2020-04-14  the lowest positve error was by the method: mlb and the highest negative error by the method: mb
for date: 2020-04-15  the lowest positve error was by the method: mlb and the highest negative error by the method: mb
for date: 2020-04-16  the lowest positve error was by the method: lmb and the highest negative error by the method: mlb
for date: 2020-04-17  the lowest positve error was by the method: mb and the highest negative error by the method: memb
for date: 2020-04-18  the lowest positve error was by the method: mb and the highest negative error by the method: mb
for date: 2020-04-19  the lowest positve error was by the method: mlb and the highest negative error by the method: memb
for date: 2020-04-20  the lowest positve error was by the method: mb and the highest negative error by the method: lmb
for date: 2020-04-21  the lowest positve error was by the method: mxmb and the highest negative error by the method: mxb
for date: 2020-04-22  the lowest positve error was by the method: mdb and the highest negative error by the method: mb
for date: 2020-04-23  the lowest positve error was by the method: mb and the highest negative error by the method: mdb
for date: 2020-04-24  the lowest positve error was by the method: memb and the highest negative error by the method: mxmb
for date: 2020-04-25  the lowest positve error was by the method: memb and the highest negative error by the method: mb
for date: 2020-04-26  the lowest positve error was by the method: mlb and the highest negative error by the method: memb
for date: 2020-04-27  the lowest positve error was by the method: lmb and the highest negative error by the method: mlb
for date: 2020-04-28  the lowest positve error was by the method: memb and the highest negative error by the method: mxmb
for date: 2020-04-29  the lowest positve error was by the method: lmb and the highest negative error by the method: memb
for date: 2020-04-30  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-05-01  the lowest positve error was by the method: mb and the highest negative error by the method: lb
for date: 2020-05-02  the lowest positve error was by the method: mxmb and the highest negative error by the method: mxb
for date: 2020-05-03  the lowest positve error was by the method: mxb and the highest negative error by the method: mxb
for date: 2020-05-04  the lowest positve error was by the method: mb and the highest negative error by the method: mxmb
for date: 2020-05-05  the lowest positve error was by the method: mlb and the highest negative error by the method: mxmb
for date: 2020-05-06  the lowest positve error was by the method: mlb and the highest negative error by the method: mb
for date: 2020-05-07  the lowest positve error was by the method: mlb and the highest negative error by the method: mb
for date: 2020-05-08  the lowest positve error was by the method: mdb and the highest negative error by the method: mlb
for date: 2020-05-09  the lowest positve error was by the method: mb and the highest negative error by the method: memb
for date: 2020-05-10  the lowest positve error was by the method: mdb and the highest negative error by the method: mb
for date: 2020-05-11  the lowest positve error was by the method: mdb and the highest negative error by the method: lmb
for date: 2020-05-12  the lowest positve error was by the method: mb and the highest negative error by the method: memb
for date: 2020-05-13  the lowest positve error was by the method: mdb and the highest negative error by the method: mxmb
for date: 2020-05-14  the lowest positve error was by the method: mdb and the highest negative error by the method: mdb
for date: 2020-05-15  the lowest positve error was by the method: mlb and the highest negative error by the method: mb
for date: 2020-05-16  the lowest positve error was by the method: lmb and the highest negative error by the method: memb
for date: 2020-05-17  the lowest positve error was by the method: memb and the highest negative error by the method: mdb
for date: 2020-05-18  the lowest positve error was by the method: mb and the highest negative error by the method: lmb
for date: 2020-05-19  the lowest positve error was by the method: mlb and the highest negative error by the method: memb
for date: 2020-05-20  the lowest positve error was by the method: mb and the highest negative error by the method: mdb
for date: 2020-05-21  the lowest positve error was by the method: mlb and the highest negative error by the method: memb
for date: 2020-05-22  the lowest positve error was by the method: mdb and the highest negative error by the method: mb
for date: 2020-05-23  the lowest positve error was by the method: lb and the highest negative error by the method: mb
for date: 2020-05-24  the lowest positve error was by the method: mb and the highest negative error by the method: memb
for date: 2020-05-25  the lowest positve error was by the method: mb and the highest negative error by the method: memb
for date: 2020-05-26  the lowest positve error was by the method: mxmb and the highest negative error by the method: mxb
for date: 2020-05-27  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-05-28  the lowest positve error was by the method: lmb and the highest negative error by the method: mxmb
for date: 2020-05-29  the lowest positve error was by the method: mxb and the highest negative error by the method: mxmb
for date: 2020-05-30  the lowest positve error was by the method: mdb and the highest negative error by the method: mxmb
for date: 2020-05-31  the lowest positve error was by the method: mlb and the highest negative error by the method: mxmb
for date: 2020-06-01  the lowest positve error was by the method: mdb and the highest negative error by the method: mb
for date: 2020-06-02  the lowest positve error was by the method: mb and the highest negative error by the method: memb
for date: 2020-06-03  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-06-04  the lowest positve error was by the method: lmb and the highest negative error by the method: mlb
for date: 2020-06-05  the lowest positve error was by the method: mb and the highest negative error by the method: lb
for date: 2020-06-06  the lowest positve error was by the method: memb and the highest negative error by the method: lb
for date: 2020-06-07  the lowest positve error was by the method: lmb and the highest negative error by the method: mb
for date: 2020-06-08  the lowest positve error was by the method: mlb and the highest negative error by the method: mdb
for date: 2020-06-09  the lowest positve error was by the method: mlb and the highest negative error by the method: lmb
for date: 2020-06-10  the lowest positve error was by the method: mxb and the highest negative error by the method: lmb
for date: 2020-06-11  the lowest positve error was by the method: mxmb and the highest negative error by the method: mxb
for date: 2020-06-12  the lowest positve error was by the method: lmb and the highest negative error by the method: mxmb
for date: 2020-06-13  the lowest positve error was by the method: mdb and the highest negative error by the method: lmb
for date: 2020-06-14  the lowest positve error was by the method: mlb and the highest negative error by the method: mb
for date: 2020-06-15  the lowest positve error was by the method: lmb and the highest negative error by the method: memb
for date: 2020-06-16  the lowest positve error was by the method: mxb and the highest negative error by the method: memb
for date: 2020-06-17  the lowest positve error was by the method: mdb and the highest negative error by the method: mb
for date: 2020-06-18  the lowest positve error was by the method: mdb and the highest negative error by the method: mlb
for date: 2020-06-19  the lowest positve error was by the method: lb and the highest negative error by the method: mdb
for date: 2020-06-20  the lowest positve error was by the method: lb and the highest negative error by the method: lb
for date: 2020-06-21  the lowest positve error was by the method: lb and the highest negative error by the method: mlb
for date: 2020-06-22  the lowest positve error was by the method: lb and the highest negative error by the method: mdb
for date: 2020-06-23  the lowest positve error was by the method: mlb and the highest negative error by the method: mb
for date: 2020-06-24  the lowest positve error was by the method: mb and the highest negative error by the method: memb
for date: 2020-06-25  the lowest positve error was by the method: mb and the highest negative error by the method: mlb
for date: 2020-06-26  the lowest positve error was by the method: lb and the highest negative error by the method: mb
for date: 2020-06-27  the lowest positve error was by the method: mb and the highest negative error by the method: memb
for date: 2020-06-28  the lowest positve error was by the method: mdb and the highest negative error by the method: mb
for date: 2020-06-29  the lowest positve error was by the method: mb and the highest negative error by the method: memb
for date: 2020-06-30  the lowest positve error was by the method: memb and the highest negative error by the method: mxmb
for date: 2020-07-01  the lowest positve error was by the method: mb and the highest negative error by the method: mdb
for date: 2020-07-02  the lowest positve error was by the method: lmb and the highest negative error by the method: lb
for date: 2020-07-03  the lowest positve error was by the method: mb and the highest negative error by the method: mdb
for date: 2020-07-04  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-07-05  the lowest positve error was by the method: mdb and the highest negative error by the method: mb
for date: 2020-07-06  the lowest positve error was by the method: mlb and the highest negative error by the method: mb
for date: 2020-07-07  the lowest positve error was by the method: mlb and the highest negative error by the method: mb
for date: 2020-07-08  the lowest positve error was by the method: mlb and the highest negative error by the method: memb
for date: 2020-07-09  the lowest positve error was by the method: mdb and the highest negative error by the method: lmb
for date: 2020-07-10  the lowest positve error was by the method: mb and the highest negative error by the method: mdb
for date: 2020-07-11  the lowest positve error was by the method: mlb and the highest negative error by the method: lb
for date: 2020-07-12  the lowest positve error was by the method: mb and the highest negative error by the method: mdb
for date: 2020-07-13  the lowest positve error was by the method: mlb and the highest negative error by the method: memb
for date: 2020-07-14  the lowest positve error was by the method: lb and the highest negative error by the method: mxb
for date: 2020-07-15  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-07-16  the lowest positve error was by the method: mxb and the highest negative error by the method: mxb
for date: 2020-07-17  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-07-18  the lowest positve error was by the method: mxmb and the highest negative error by the method: lmb
for date: 2020-07-19  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-07-20  the lowest positve error was by the method: mxmb and the highest negative error by the method: mb
for date: 2020-07-21  the lowest positve error was by the method: mb and the highest negative error by the method: mdb
for date: 2020-07-22  the lowest positve error was by the method: mxb and the highest negative error by the method: mdb
for date: 2020-07-23  the lowest positve error was by the method: mxb and the highest negative error by the method: mb
for date: 2020-07-24  the lowest positve error was by the method: mb and the highest negative error by the method: mlb
for date: 2020-07-25  the lowest positve error was by the method: mb and the highest negative error by the method: lmb
for date: 2020-07-26  the lowest positve error was by the method: lmb and the highest negative error by the method: mlb
for date: 2020-07-27  the lowest positve error was by the method: mdb and the highest negative error by the method: lb
for date: 2020-07-28  the lowest positve error was by the method: mdb and the highest negative error by the method: mb
for date: 2020-07-29  the lowest positve error was by the method: mdb and the highest negative error by the method: mlb
for date: 2020-07-30  the lowest positve error was by the method: lb and the highest negative error by the method: mxmb
for date: 2020-07-31  the lowest positve error was by the method: lmb and the highest negative error by the method: memb
for date: 2020-08-01  the lowest positve error was by the method: memb and the highest negative error by the method: mxmb
for date: 2020-08-02  the lowest positve error was by the method: memb and the highest negative error by the method: mdb
for date: 2020-08-03  the lowest positve error was by the method: mdb and the highest negative error by the method: memb
for date: 2020-08-04  the lowest positve error was by the method: mlb and the highest negative error by the method: lb
for date: 2020-08-05  the lowest positve error was by the method: lb and the highest negative error by the method: mxb
for date: 2020-08-06  the lowest positve error was by the method: lmb and the highest negative error by the method: mxmb
for date: 2020-08-07  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-08-08  the lowest positve error was by the method: mxmb and the highest negative error by the method: mb
for date: 2020-08-09  the lowest positve error was by the method: mxb and the highest negative error by the method: mb
for date: 2020-08-10  the lowest positve error was by the method: mdb and the highest negative error by the method: mb
for date: 2020-08-11  the lowest positve error was by the method: lmb and the highest negative error by the method: mlb
for date: 2020-08-12  the lowest positve error was by the method: mb and the highest negative error by the method: memb
for date: 2020-08-13  the lowest positve error was by the method: mlb and the highest negative error by the method: memb
for date: 2020-08-14  the lowest positve error was by the method: lmb and the highest negative error by the method: mlb
for date: 2020-08-15  the lowest positve error was by the method: mb and the highest negative error by the method: lb
for date: 2020-08-16  the lowest positve error was by the method: lb and the highest negative error by the method: mb
for date: 2020-08-17  the lowest positve error was by the method: lb and the highest negative error by the method: mb
for date: 2020-08-18  the lowest positve error was by the method: mxmb and the highest negative error by the method: mxb
for date: 2020-08-19  the lowest positve error was by the method: mdb and the highest negative error by the method: mb
for date: 2020-08-20  the lowest positve error was by the method: mdb and the highest negative error by the method: mb
for date: 2020-08-21  the lowest positve error was by the method: mdb and the highest negative error by the method: mb
for date: 2020-08-22  the lowest positve error was by the method: mdb and the highest negative error by the method: lb
for date: 2020-08-23  the lowest positve error was by the method: mdb and the highest negative error by the method: mdb
for date: 2020-08-24  the lowest positve error was by the method: mlb and the highest negative error by the method: lmb
for date: 2020-08-25  the lowest positve error was by the method: lmb and the highest negative error by the method: memb
for date: 2020-08-26  the lowest positve error was by the method: mb and the highest negative error by the method: memb
for date: 2020-08-27  the lowest positve error was by the method: mlb and the highest negative error by the method: memb
for date: 2020-08-28  the lowest positve error was by the method: lmb and the highest negative error by the method: memb
for date: 2020-08-29  the lowest positve error was by the method: lmb and the highest negative error by the method: lb
for date: 2020-08-30  the lowest positve error was by the method: mlb and the highest negative error by the method: mdb
for date: 2020-08-31  the lowest positve error was by the method: mlb and the highest negative error by the method: lb
for date: 2020-09-01  the lowest positve error was by the method: lmb and the highest negative error by the method: mdb
for date: 2020-09-02  the lowest positve error was by the method: mdb and the highest negative error by the method: mb
for date: 2020-09-03  the lowest positve error was by the method: mdb and the highest negative error by the method: mxmb
for date: 2020-09-04  the lowest positve error was by the method: mb and the highest negative error by the method: mlb
for date: 2020-09-05  the lowest positve error was by the method: mb and the highest negative error by the method: lb
for date: 2020-09-06  the lowest positve error was by the method: mxmb and the highest negative error by the method: mxb
for date: 2020-09-07  the lowest positve error was by the method: mxb and the highest negative error by the method: mxb
for date: 2020-09-08  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-09-09  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-09-10  the lowest positve error was by the method: memb and the highest negative error by the method: lb
for date: 2020-09-11  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-09-12  the lowest positve error was by the method: lmb and the highest negative error by the method: mb

In [33]:
err_dict={"date":[],"mipe":[],"mxne":[],"mipv":[],"mxnv":[],"original_val":[],"pprd_val":[],"nprd_val":[]}
psc=[]
ngc=[]
date=[]
ps=[]
ng=[]
org_val=[]
pprd_val=[]
nprd_val=[]
for j,k in zip(range(len(edf)),range(len(dce))):
    
    a=list(edf.loc[j])
    pos=[]
    neg=[]
    for i in a:
        if(i>=0):
            pos.append(i)
        else:
            neg.append(i)
    if(len(pos)):
        aa=min(pos)
    
        psi=a.index(aa)
    
        ps.append(aa)
    
        psc.append(list(edf.columns)[psi])
    
    
        pprd_val.append(dce["original_val"][k]-aa)
    else:
        ps.append("No")
    
        psc.append("No")
    
    
        pprd_val.append("No")
        
    
    if(len(neg)):
        bb=max(neg)
        ngi=a.index(bb)
        ng.append(bb)
        ngc.append(list(edf.columns)[ngi])
        nprd_val.append(dce["original_val"][k]-bb)
    else:
        ng.append("No")
    
        ngc.append("No")
    
    
        nprd_val.append("No")
    
    date.append(str(dce["date"][k]).strip("00:00:00"))
    org_val.append(dce["original_val"][k])
err_dict.update({"date":date})
err_dict.update({"mipe":psc})
err_dict.update({"mxne":ngc})
err_dict.update({"mipv":ps})
err_dict.update({"mxnv":ng})
err_dict.update({"original_val":org_val})
err_dict.update({"pprd_val":pprd_val})
err_dict.update({"nprd_val":nprd_val})

In [34]:
err_dict

{'date': ['2020-03-31 ',
  '2020-04-01 ',
  '2020-04-02 ',
  '2020-04-03 ',
  '2020-04-04 ',
  '2020-04-05 ',
  '2020-04-06 ',
  '2020-04-07 ',
  '2020-04-08 ',
  '2020-04-09 ',
  '2020-04-10 ',
  '2020-04-11 ',
  '2020-04-12 ',
  '2020-04-13 ',
  '2020-04-14 ',
  '2020-04-15 ',
  '2020-04-16 ',
  '2020-04-17 ',
  '2020-04-18 ',
  '2020-04-19 ',
  '2020-04-20 ',
  '2020-04-21 ',
  '2020-04-22 ',
  '2020-04-23 ',
  '2020-04-24 ',
  '2020-04-25 ',
  '2020-04-26 ',
  '2020-04-27 ',
  '2020-04-28 ',
  '2020-04-29 ',
  '2020-04-30 ',
  '2020-05-01 ',
  '2020-05-02 ',
  '2020-05-03 ',
  '2020-05-04 ',
  '2020-05-05 ',
  '2020-05-06 ',
  '2020-05-07 ',
  '2020-05-08 ',
  '2020-05-09 ',
  '2020-05-10 ',
  '2020-05-11 ',
  '2020-05-12 ',
  '2020-05-13 ',
  '2020-05-14 ',
  '2020-05-15 ',
  '2020-05-16 ',
  '2020-05-17 ',
  '2020-05-18 ',
  '2020-05-19 ',
  '2020-05-20 ',
  '2020-05-21 ',
  '2020-05-22 ',
  '2020-05-23 ',
  '2020-05-24 ',
  '2020-05-25 ',
  '2020-05-26 ',
  '2020-05-27 ',
  '2020-05-28 ',
  '2020-05-29 ',
  '2020-05-30 ',
  '2020-05-31 ',
  '2020-06-01 ',
  '2020-06-02 ',
  '2020-06-03 ',
  '2020-06-04 ',
  '2020-06-05 ',
  '2020-06-06 ',
  '2020-06-07 ',
  '2020-06-08 ',
  '2020-06-09 ',
  '2020-06-10 ',
  '2020-06-11 ',
  '2020-06-12 ',
  '2020-06-13 ',
  '2020-06-14 ',
  '2020-06-15 ',
  '2020-06-16 ',
  '2020-06-17 ',
  '2020-06-18 ',
  '2020-06-19 ',
  '2020-06-20 ',
  '2020-06-21 ',
  '2020-06-22 ',
  '2020-06-23 ',
  '2020-06-24 ',
  '2020-06-25 ',
  '2020-06-26 ',
  '2020-06-27 ',
  '2020-06-28 ',
  '2020-06-29 ',
  '2020-06-30 ',
  '2020-07-01 ',
  '2020-07-02 ',
  '2020-07-03 ',
  '2020-07-04 ',
  '2020-07-05 ',
  '2020-07-06 ',
  '2020-07-07 ',
  '2020-07-08 ',
  '2020-07-09 ',
  '2020-07-10 ',
  '2020-07-11 ',
  '2020-07-12 ',
  '2020-07-13 ',
  '2020-07-14 ',
  '2020-07-15 ',
  '2020-07-16 ',
  '2020-07-17 ',
  '2020-07-18 ',
  '2020-07-19 ',
  '2020-07-20 ',
  '2020-07-21 ',
  '2020-07-22 ',
  '2020-07-23 ',
  '2020-07-24 ',
  '2020-07-25 ',
  '2020-07-26 ',
  '2020-07-27 ',
  '2020-07-28 ',
  '2020-07-29 ',
  '2020-07-30 ',
  '2020-07-31 ',
  '2020-08-01 ',
  '2020-08-02 ',
  '2020-08-03 ',
  '2020-08-04 ',
  '2020-08-05 ',
  '2020-08-06 ',
  '2020-08-07 ',
  '2020-08-08 ',
  '2020-08-09 ',
  '2020-08-10 ',
  '2020-08-11 ',
  '2020-08-12 ',
  '2020-08-13 ',
  '2020-08-14 ',
  '2020-08-15 ',
  '2020-08-16 ',
  '2020-08-17 ',
  '2020-08-18 ',
  '2020-08-19 ',
  '2020-08-20 ',
  '2020-08-21 ',
  '2020-08-22 ',
  '2020-08-23 ',
  '2020-08-24 ',
  '2020-08-25 ',
  '2020-08-26 ',
  '2020-08-27 ',
  '2020-08-28 ',
  '2020-08-29 ',
  '2020-08-30 ',
  '2020-08-31 ',
  '2020-09-01 ',
  '2020-09-02 ',
  '2020-09-03 ',
  '2020-09-04 ',
  '2020-09-05 ',
  '2020-09-06 ',
  '2020-09-07 ',
  '2020-09-08 ',
  '2020-09-09 ',
  '2020-09-10 ',
  '2020-09-11 ',
  '2020-09-12 ',
  '2020-09-13 ',
  '2020-09-14 ',
  '2020-09-15 ',
  '2020-09-16 ',
  '2020-09-17 ',
  '2020-09-18 ',
  '2020-09-19 ',
  '2020-09-20 ',
  '2020-09-21 ',
  '2020-09-22 ',
  '2020-09-23 ',
  '2020-09-24 ',
  '2020-09-25 ',
  '2020-09-26 ',
  '2020-09-27 ',
  '2020-09-28 ',
  '2020-09-29 ',
  '2020-09-30 ',
  '2020-10-01 ',
  '2020-10-02 ',
  '2020-10-03 ',
  '2020-10-04 ',
  '2020-10-05 ',
  '2020-10-06 ',
  '2020-10-07 ',
  '2020-10-08 ',
  '2020-10-09 ',
  '2020-10-10 ',
  '2020-10-11 ',
  '2020-10-12 ',
  '2020-10-13 ',
  '2020-10-14 ',
  '2020-10-15 ',
  '2020-10-16 ',
  '2020-10-17 '],
 'mipe': ['mdb',
  'lb',
  'mb',
  'mb',
  'lb',
  'mlb',
  'No',
  'memb',
  'mdb',
  'mdb',
  'mdb',
  'mb',
  'mb',
  'No',
  'mlb',
  'No',
  'lmb',
  'mb',
  'No',
  'mlb',
  'mb',
  'mxmb',
  'mdb',
  'mb',
  'memb',
  'No',
  'mlb',
  'lmb',
  'memb',
  'lmb',
  'lb',
  'mb',
  'mxmb',
  'mxb',
  'mb',
  'mlb',
  'No',
  'mlb',
  'mdb',
  'mb',
  'mdb',
  'No',
  'mb',
  'mdb',
  'No',
  'mlb',
  'lmb',
  'memb',
  'mb',
  'mlb',
  'mb',
  'mlb',
  'mdb',
  'lb',
  'mb',
  'mb',
  'mxmb',
  'memb',
  'lmb',
  'mxb',
  'mdb',
  'mlb',
  'mdb',
  'mb',
  'lb',
  'lmb',
  'mb',
  'memb',
  'lmb',
  'mlb',
  'No',
  'mxb',
  'mxmb',
  'lmb',
  'mdb',
  'mlb',
  'lmb',
  'mxb',
  'mdb',
  'mdb',
  'lb',
  'No',
  'lb',
  'No',
  'mlb',
  'mb',
  'mb',
  'lb',
  'mb',
  'mdb',
  'mb',
  'memb',
  'mb',
  'lmb',
  'mb',
  'memb',
  'mdb',
  'mlb',
  'No',
  'mlb',
  'mdb',
  'mb',
  'mlb',
  'mb',
  'mlb',
  'lb',
  'memb',
  'mxb',
  'mxmb',
  'No',
  'mxmb',
  'No',
  'mb',
  'mxb',
  'No',
  'mb',
  'No',
  'lmb',
  'mdb',
  'mdb',
  'mdb',
  'lb',
  'lmb',
  'memb',
  'No',
  'mdb',
  'mlb',
  'lb',
  'lmb',
  'mxmb',
  'No',
  'mxb',
  'mdb',
  'lmb',
  'mb',
  'mlb',
  'lmb',
  'mb',
  'lb',
  'No',
  'mxmb',
  'mdb',
  'mdb',
  'mdb',
  'No',
  'No',
  'mlb',
  'lmb',
  'mb',
  'mlb',
  'lmb',
  'lmb',
  'mlb',
  'No',
  'lmb',
  'mdb',
  'mdb',
  'mb',
  'mb',
  'mxmb',
  'mxb',
  'mxmb',
  'memb',
  'memb',
  'mxmb',
  'lmb',
  'lmb',
  'No',
  'mxb',
  'mdb',
  'mdb',
  'lb',
  'No',
  'lmb',
  'No',
  'lmb',
  'lb',
  'mb',
  'mdb',
  'mdb',
  'No',
  'No',
  'memb',
  'mdb',
  'lmb',
  'lb',
  'No',
  'lb',
  'lb',
  'mlb',
  'mdb',
  'mb',
  'mdb',
  'mlb',
  'No',
  'No',
  'mlb',
  'No',
  'mxmb',
  'mb',
  'No'],
 'mxne': ['mb',
  'mdb',
  'memb',
  'lmb',
  'mb',
  'memb',
  'lmb',
  'mxmb',
  'mb',
  'mxmb',
  'mb',
  'mdb',
  'lmb',
  'lmb',
  'mb',
  'mb',
  'mlb',
  'memb',
  'mb',
  'memb',
  'lmb',
  'mxb',
  'mb',
  'mdb',
  'mxmb',
  'mb',
  'memb',
  'mlb',
  'mxmb',
  'memb',
  'memb',
  'lb',
  'mxb',
  'No',
  'mxmb',
  'mxmb',
  'mb',
  'mb',
  'mlb',
  'memb',
  'mb',
  'lmb',
  'memb',
  'mxmb',
  'mdb',
  'mb',
  'memb',
  'mdb',
  'lmb',
  'memb',
  'mdb',
  'memb',
  'mb',
  'mb',
  'memb',
  'memb',
  'mxb',
  'mxb',
  'mxmb',
  'No',
  'mxmb',
  'mxmb',
  'mb',
  'memb',
  'memb',
  'mlb',
  'lb',
  'lb',
  'mb',
  'mdb',
  'lmb',
  'No',
  'mxb',
  'mxmb',
  'lmb',
  'mb',
  'memb',
  'No',
  'mb',
  'mlb',
  'mdb',
  'lb',
  'mlb',
  'mdb',
  'mb',
  'memb',
  'mlb',
  'mb',
  'memb',
  'mb',
  'memb',
  'mxmb',
  'mdb',
  'lb',
  'mdb',
  'mxb',
  'mb',
  'mb',
  'mb',
  'memb',
  'lmb',
  'mdb',
  'lb',
  'mdb',
  'memb',
  'mxb',
  'mxb',
  'No',
  'memb',
  'lmb',
  'memb',
  'mb',
  'mdb',
  'No',
  'mb',
  'mlb',
  'lmb',
  'mlb',
  'lb',
  'mb',
  'mlb',
  'mxmb',
  'memb',
  'mxmb',
  'mdb',
  'memb',
  'lb',
  'mxb',
  'mxmb',
  'memb',
  'mb',
  'No',
  'mb',
  'mlb',
  'memb',
  'memb',
  'mlb',
  'lb',
  'mb',
  'mb',
  'mxb',
  'mb',
  'mb',
  'mb',
  'lb',
  'mdb',
  'lmb',
  'memb',
  'memb',
  'memb',
  'memb',
  'lb',
  'mdb',
  'lb',
  'mdb',
  'mb',
  'mxmb',
  'mlb',
  'lb',
  'mxb',
  'No',
  'memb',
  'mxb',
  'lb',
  'memb',
  'mb',
  'mlb',
  'mlb',
  'No',
  'mb',
  'memb',
  'memb',
  'mb',
  'mlb',
  'lb',
  'mb',
  'lmb',
  'lb',
  'mb',
  'memb',
  'mb',
  'lb',
  'mxb',
  'memb',
  'mb',
  'mb',
  'lmb',
  'lmb',
  'mlb',
  'lmb',
  'mlb',
  'memb',
  'mb',
  'mb',
  'lb',
  'lb',
  'lmb',
  'mlb',
  'memb',
  'mlb',
  'mdb'],
 'mipv': [4,
  3,
  4,
  1,
  1,
  1,
  'No',
  1,
  8,
  9,
  10,
  12,
  4,
  'No',
  3,
  'No',
  1,
  6,
  'No',
  2,
  0,
  4,
  4,
  0,
  0,
  'No',
  8,
  0,
  2,
  9,
  2,
  8,
  10,
  23,
  7,
  14,
  'No',
  7,
  21,
  0,
  47,
  'No',
  17,
  1,
  'No',
  5,
  3,
  10,
  6,
  2,
  2,
  12,
  29,
  6,
  9,
  6,
  11,
  10,
  5,
  52,
  5,
  2,
  36,
  4,
  14,
  15,
  30,
  6,
  0,
  3,
  'No',
  12,
  14,
  52,
  36,
  10,
  49,
  1483,
  95,
  3,
  19,
  'No',
  165,
  'No',
  11,
  74,
  0,
  2,
  11,
  0,
  17,
  11,
  13,
  14,
  28,
  89,
  42,
  36,
  'No',
  6,
  189,
  8,
  2,
  16,
  28,
  2,
  9,
  13,
  46,
  'No',
  20,
  'No',
  32,
  285,
  'No',
  1,
  'No',
  7,
  138,
  3,
  127,
  8,
  20,
  67,
  'No',
  13,
  13,
  25,
  12,
  2,
  'No',
  0,
  8,
  37,
  39,
  47,
  5,
  4,
  36,
  'No',
  32,
  63,
  29,
  140,
  'No',
  'No',
  17,
  110,
  74,
  39,
  13,
  16,
  9,
  'No',
  56,
  40,
  2,
  26,
  0,
  2,
  26,
  18,
  2,
  1,
  0,
  15,
  92,
  'No',
  1,
  113,
  5,
  10,
  'No',
  38,
  'No',
  1,
  8,
  11,
  111,
  9,
  'No',
  'No',
  77,
  23,
  22,
  44,
  'No',
  81,
  16,
  73,
  141,
  15,
  60,
  8,
  'No',
  'No',
  33,
  'No',
  40,
  34,
  'No'],
 'mxnv': [-3,
  -2,
  -12,
  -6,
  -3,
  -4,
  -6,
  -8,
  -2,
  -3,
  -7,
  -5,
  -10,
  -4,
  -3,
  -13,
  -6,
  -4,
  -4,
  -5,
  -2,
  -3,
  -3,
  -1,
  -4,
  -2,
  -8,
  -4,
  -10,
  -3,
  -5,
  -2,
  -6,
  'No',
  -24,
  -8,
  -18,
  -4,
  -16,
  -35,
  -7,
  -23,
  -6,
  -15,
  -12,
  -7,
  -23,
  -4,
  -16,
  -21,
  -4,
  -6,
  -1,
  -5,
  -1,
  -7,
  -1,
  -12,
  -5,
  'No',
  -69,
  -66,
  -11,
  -64,
  -26,
  -3,
  -4,
  -2,
  -5,
  -19,
  -5,
  'No',
  -77,
  -14,
  -6,
  -3,
  -14,
  'No',
  -641,
  -163,
  -120,
  -78,
  -32,
  -33,
  -390,
  -24,
  -49,
  -26,
  -72,
  -49,
  -54,
  -113,
  -12,
  -1,
  -9,
  -3,
  -66,
  -4,
  -9,
  -128,
  -5,
  -11,
  -22,
  -5,
  -17,
  -2,
  -23,
  'No',
  -40,
  -45,
  -9,
  -52,
  -1,
  'No',
  -40,
  -35,
  -38,
  -53,
  -63,
  -28,
  -44,
  -97,
  -27,
  -32,
  -16,
  -62,
  -6,
  -36,
  -17,
  -4,
  -13,
  'No',
  -52,
  -68,
  -65,
  -17,
  -38,
  -20,
  -11,
  -53,
  -46,
  -40,
  -8,
  -25,
  -8,
  -26,
  -22,
  -34,
  -50,
  -11,
  -65,
  -31,
  -10,
  -161,
  -82,
  -25,
  -53,
  -20,
  -6,
  -65,
  'No',
  -77,
  -100,
  -19,
  -51,
  -34,
  -4,
  -109,
  'No',
  -56,
  -108,
  -60,
  -20,
  -25,
  -65,
  -86,
  -46,
  -18,
  -34,
  -8,
  -66,
  -187,
  -6,
  -37,
  -7,
  -18,
  -99,
  -9,
  -18,
  -26,
  -5,
  -103,
  -15,
  -2,
  -100,
  -8,
  -62,
  -2,
  -42,
  -37,
  -744],
 'original_val': [6,
  6,
  16,
  14,
  13,
  22,
  16,
  27,
  20,
  46,
  22,
  41,
  42,
  27,
  37,
  27,
  26,
  38,
  35,
  38,
  33,
  53,
  36,
  40,
  59,
  44,
  56,
  58,
  69,
  71,
  75,
  77,
  92,
  140,
  103,
  128,
  91,
  104,
  97,
  115,
  112,
  81,
  120,
  137,
  97,
  104,
  120,
  152,
  131,
  146,
  134,
  148,
  142,
  142,
  156,
  150,
  173,
  188,
  176,
  269,
  205,
  222,
  201,
  222,
  259,
  274,
  286,
  297,
  261,
  271,
  272,
  358,
  394,
  388,
  309,
  324,
  396,
  2004,
  341,
  343,
  364,
  308,
  426,
  312,
  468,
  424,
  401,
  381,
  414,
  384,
  417,
  506,
  438,
  378,
  444,
  611,
  421,
  473,
  479,
  492,
  479,
  520,
  543,
  500,
  541,
  587,
  614,
  680,
  676,
  543,
  675,
  596,
  671,
  1130,
  755,
  763,
  703,
  704,
  642,
  774,
  775,
  784,
  764,
  854,
  760,
  806,
  849,
  919,
  899,
  936,
  875,
  1013,
  887,
  835,
  950,
  1006,
  989,
  952,
  952,
  880,
  1099,
  979,
  981,
  953,
  918,
  846,
  854,
  1066,
  1017,
  1066,
  1019,
  943,
  960,
  816,
  892,
  913,
  979,
  950,
  916,
  1005,
  1129,
  1107,
  1168,
  1213,
  1202,
  1111,
  1140,
  1054,
  1281,
  1140,
  1175,
  1221,
  1149,
  1135,
  1056,
  1085,
  1123,
  1144,
  1093,
  1124,
  1040,
  775,
  1178,
  1179,
  1099,
  1068,
  937,
  903,
  886,
  990,
  963,
  967,
  929,
  921,
  813,
  710,
  723,
  690,
  882,
  840,
  0],
 'pprd_val': [2,
  3,
  12,
  13,
  12,
  21,
  'No',
  26,
  12,
  37,
  12,
  29,
  38,
  'No',
  34,
  'No',
  25,
  32,
  'No',
  36,
  33,
  49,
  32,
  40,
  59,
  'No',
  48,
  58,
  67,
  62,
  73,
  69,
  82,
  117,
  96,
  114,
  'No',
  97,
  76,
  115,
  65,
  'No',
  103,
  136,
  'No',
  99,
  117,
  142,
  125,
  144,
  132,
  136,
  113,
  136,
  147,
  144,
  162,
  178,
  171,
  217,
  200,
  220,
  165,
  218,
  245,
  259,
  256,
  291,
  261,
  268,
  'No',
  346,
  380,
  336,
  273,
  314,
  347,
  521,
  246,
  340,
  345,
  'No',
  261,
  'No',
  457,
  350,
  401,
  379,
  403,
  384,
  400,
  495,
  425,
  364,
  416,
  522,
  379,
  437,
  'No',
  486,
  290,
  512,
  541,
  484,
  513,
  585,
  605,
  667,
  630,
  'No',
  655,
  'No',
  639,
  845,
  'No',
  762,
  'No',
  697,
  504,
  771,
  648,
  776,
  744,
  787,
  'No',
  793,
  836,
  894,
  887,
  934,
  'No',
  1013,
  879,
  798,
  911,
  959,
  984,
  948,
  916,
  'No',
  1067,
  916,
  952,
  813,
  'No',
  'No',
  837,
  956,
  943,
  1027,
  1006,
  927,
  951,
  'No',
  836,
  873,
  977,
  924,
  916,
  1003,
  1103,
  1089,
  1166,
  1212,
  1202,
  1096,
  1048,
  'No',
  1280,
  1027,
  1170,
  1211,
  'No',
  1097,
  'No',
  1084,
  1115,
  1133,
  982,
  1115,
  'No',
  'No',
  1101,
  1156,
  1077,
  1024,
  'No',
  822,
  870,
  917,
  822,
  952,
  869,
  913,
  'No',
  'No',
  690,
  'No',
  842,
  806,
  'No'],
 'nprd_val': [9,
  8,
  28,
  20,
  16,
  26,
  22,
  35,
  22,
  49,
  29,
  46,
  52,
  31,
  40,
  40,
  32,
  42,
  39,
  43,
  35,
  56,
  39,
  41,
  63,
  46,
  64,
  62,
  79,
  74,
  80,
  79,
  98,
  'No',
  127,
  136,
  109,
  108,
  113,
  150,
  119,
  104,
  126,
  152,
  109,
  111,
  143,
  156,
  147,
  167,
  138,
  154,
  143,
  147,
  157,
  157,
  174,
  200,
  181,
  'No',
  274,
  288,
  212,
  286,
  285,
  277,
  290,
  299,
  266,
  290,
  277,
  'No',
  471,
  402,
  315,
  327,
  410,
  'No',
  982,
  506,
  484,
  386,
  458,
  345,
  858,
  448,
  450,
  407,
  486,
  433,
  471,
  619,
  450,
  379,
  453,
  614,
  487,
  477,
  488,
  620,
  484,
  531,
  565,
  505,
  558,
  589,
  637,
  'No',
  716,
  588,
  684,
  648,
  672,
  'No',
  795,
  798,
  741,
  757,
  705,
  802,
  819,
  881,
  791,
  886,
  776,
  868,
  855,
  955,
  916,
  940,
  888,
  'No',
  939,
  903,
  1015,
  1023,
  1027,
  972,
  963,
  933,
  1145,
  1019,
  989,
  978,
  926,
  872,
  876,
  1100,
  1067,
  1077,
  1084,
  974,
  970,
  977,
  974,
  938,
  1032,
  970,
  922,
  1070,
  'No',
  1184,
  1268,
  1232,
  1253,
  1145,
  1144,
  1163,
  'No',
  1196,
  1283,
  1281,
  1169,
  1160,
  1121,
  1171,
  1169,
  1162,
  1127,
  1132,
  1106,
  962,
  1184,
  1216,
  1106,
  1086,
  1036,
  912,
  904,
  1016,
  968,
  1070,
  944,
  923,
  913,
  718,
  785,
  692,
  924,
  877,
  744]}

In [35]:
err_df=pd.DataFrame(err_dict)
err_df

            date  mipe  mxne mipv  mxnv  original_val pprd_val nprd_val
0    2020-03-31    mdb    mb    4    -3             6        2        9
1    2020-04-01     lb   mdb    3    -2             6        3        8
2    2020-04-02     mb  memb    4   -12            16       12       28
3    2020-04-03     mb   lmb    1    -6            14       13       20
4    2020-04-04     lb    mb    1    -3            13       12       16
..           ...   ...   ...  ...   ...           ...      ...      ...
196  2020-10-13    mlb   lmb   33   -62           723      690      785
197  2020-10-14     No   mlb   No    -2           690       No      692
198  2020-10-15   mxmb  memb   40   -42           882      842      924
199  2020-10-16     mb   mlb   34   -37           840      806      877
200  2020-10-17     No   mdb   No  -744             0       No      744

[201 rows x 8 columns]

In [36]:
err_df.to_excel("dderr_df.xlsx")
errdf=pd.read_excel(r"C:\Users\Mark 1\dderr_df.xlsx")
errdf = errdf.loc[:, ~errdf.columns.str.contains('^Unnamed')]
errdf.to_excel("dderr_df.xlsx")

In [37]:
Counter(err_df['mipe'])

Counter({'mdb': 34,
         'lb': 17,
         'mb': 35,
         'mlb': 25,
         'No': 32,
         'memb': 13,
         'lmb': 24,
         'mxmb': 12,
         'mxb': 9})

In [38]:
mnval=max(list(Counter(err_df['mipe']).values()))
mnvalidx=list(Counter(err_df['mipe']).values()).index(mnval)
mnkys=list(Counter(err_df['mipe']).keys())[mnvalidx]
print("method: "+mnkys+" and values is: ",Counter(err_df['mipe'])[mnkys])

method: mb and values is:  35

In [39]:
Counter(err_df['mxne'])

Counter({'mb': 46,
         'mdb': 19,
         'memb': 41,
         'lmb': 18,
         'mxmb': 16,
         'mlb': 20,
         'mxb': 13,
         'lb': 19,
         'No': 9})

In [40]:
mxval=max(list(Counter(err_df['mxne']).values()))
mxvalidx=list(Counter(err_df['mxne']).values()).index(mxval)
mxkys=list(Counter(err_df['mxne']).keys())[mxvalidx]
print("method: "+mxkys+" and values is: ",Counter(err_df['mxne'])[mxkys])

method: mb and values is:  46

In [41]:
err_df['mipe'][len(err_df)-2]

'mb'

In [42]:
err_df['mxne'][len(err_df)-2]

'mlb'