In [1]:
import pandas as pd
import numpy as np 
import copy
from matplotlib import pyplot as plt
import seaborn as sns
from collections import *
import datetime

In [2]:
data=pd.read_csv(r"C:\Users\Mark 1\Desktop\Lockdown\data\Covid-19\117\case_time_series.csv")
data.head()

,Date,Daily Confirmed,Total Confirmed,Daily Recovered,Total Recovered,Daily Deceased,Total Deceased
0,30-Jan,1,1,0,0,0,0
1,31-Jan,0,1,0,0,0,0
2,01-Feb,0,1,0,0,0,0
3,02-Feb,1,2,0,0,0,0
4,03-Feb,1,3,0,0,0,0

In [3]:
data_daily=data[53:]
data_daily.reset_index(drop=True,inplace=True)
data_daily.head()

,Date,Daily Confirmed,Total Confirmed,Daily Recovered,Total Recovered,Daily Deceased,Total Deceased
0,23-Mar,94,497,2,25,2,9
1,24-Mar,74,571,15,40,1,10
2,25-Mar,86,657,3,43,1,11
3,26-Mar,73,730,7,50,5,16
4,27-Mar,153,883,25,75,3,19

In [4]:
data_daily.tail()

,Date,Daily Confirmed,Total Confirmed,Daily Recovered,Total Recovered,Daily Deceased,Total Deceased
214,23-Oct,53931,7813676,66994,7013541,655,117406
215,24-Oct,50366,7864042,62270,7075811,578,117984
216,25-Oct,45922,7909964,59304,7135115,483,118467
217,26-Oct,36019,7945983,63734,7198849,485,118952
218,27-Oct,43034,7989017,58428,7257277,517,119469

In [5]:
colls=list(data_daily.columns)
colls

['Date',
 'Daily Confirmed',
 'Total Confirmed',
 'Daily Recovered',
 'Total Recovered',
 'Daily Deceased',
 'Total Deceased']

In [6]:
data_daily.dtypes

Date               object
Daily Confirmed     int64
Total Confirmed     int64
Daily Recovered     int64
Total Recovered     int64
Daily Deceased      int64
Total Deceased      int64
dtype: object

In [7]:
data_daily[data_daily.duplicated()]

Empty DataFrame
Columns: [Date, Daily Confirmed, Total Confirmed, Daily Recovered, Total Recovered, Daily Deceased, Total Deceased]
Index: []

In [8]:
data_daily['Date'] = data_daily['Date'].astype('str')

<ipython-input-8-b893dc2657ae>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily['Date'] = data_daily['Date'].astype('str')

In [9]:
for i in range(0,9):
    data_daily["Date"][i]=data_daily["Date"][i].strip(" March")
for i in range(0,9):
    data_daily["Date"][i]="2020-03-"+data_daily["Date"][i]

<ipython-input-9-5d3a9c25c0f3>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]=data_daily["Date"][i].strip(" March")
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3343: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
<ipython-input-9-5d3a9c25c0f3>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]="2020-03-"+data_daily["Date"][i]

In [10]:
for i in range(9,39):
    data_daily["Date"][i]=data_daily["Date"][i].strip(" April")
for i in range(9,39):
    data_daily["Date"][i]="2020-04-"+data_daily["Date"][i]

<ipython-input-10-e708bf0423ae>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]=data_daily["Date"][i].strip(" April")
<ipython-input-10-e708bf0423ae>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]="2020-04-"+data_daily["Date"][i]

In [11]:
for i in range(39,70):
    data_daily["Date"][i]=data_daily["Date"][i].strip(" May")
for i in range(39,70):
    data_daily["Date"][i]="2020-05-"+data_daily["Date"][i]

<ipython-input-11-3a877ff4aac3>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]=data_daily["Date"][i].strip(" May")
<ipython-input-11-3a877ff4aac3>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]="2020-05-"+data_daily["Date"][i]

In [12]:
for i in range(70,100):
    data_daily["Date"][i]=data_daily["Date"][i].strip(" June")
for i in range(70,100):
    data_daily["Date"][i]="2020-06-"+data_daily["Date"][i]

<ipython-input-12-7dad98128838>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]=data_daily["Date"][i].strip(" June")
<ipython-input-12-7dad98128838>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]="2020-06-"+data_daily["Date"][i]

In [13]:
for i in range(100,131):
    data_daily["Date"][i]=data_daily["Date"][i].strip(" July")
for i in range(100,131):
    data_daily["Date"][i]="2020-07-"+data_daily["Date"][i]

<ipython-input-13-8446ec7a3871>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]=data_daily["Date"][i].strip(" July")
<ipython-input-13-8446ec7a3871>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]="2020-07-"+data_daily["Date"][i]

In [14]:
for i in range(131,162):
    data_daily["Date"][i]=data_daily["Date"][i].strip(" August")
for i in range(131,162):
    data_daily["Date"][i]="2020-08-"+data_daily["Date"][i]

<ipython-input-14-8378c44cbf95>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]=data_daily["Date"][i].strip(" August")
<ipython-input-14-8378c44cbf95>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]="2020-08-"+data_daily["Date"][i]

In [15]:
for i in range(162,192):
    data_daily["Date"][i]=data_daily["Date"][i].strip(" September")
for i in range(162,192):
    data_daily["Date"][i]="2020-09-"+data_daily["Date"][i]

<ipython-input-15-35b96d5b39bd>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]=data_daily["Date"][i].strip(" September")
<ipython-input-15-35b96d5b39bd>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]="2020-09-"+data_daily["Date"][i]

In [16]:
for i in range(192,len(data_daily)):
    data_daily["Date"][i]=data_daily["Date"][i].strip(" October")
for i in range(192,len(data_daily)):
    data_daily["Date"][i]="2020-10-"+data_daily["Date"][i]

<ipython-input-16-4fd5b8dff3d9>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]=data_daily["Date"][i].strip(" October")
<ipython-input-16-4fd5b8dff3d9>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"][i]="2020-10-"+data_daily["Date"][i]

In [17]:
data_daily["Date"]=data_daily["Date"].astype('datetime64[ns]')

<ipython-input-17-523dc667f175>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily["Date"]=data_daily["Date"].astype('datetime64[ns]')

In [18]:
data_daily.tail()

,Date,Daily Confirmed,Total Confirmed,Daily Recovered,Total Recovered,Daily Deceased,Total Deceased
214,2020-10-23,53931,7813676,66994,7013541,655,117406
215,2020-10-24,50366,7864042,62270,7075811,578,117984
216,2020-10-25,45922,7909964,59304,7135115,483,118467
217,2020-10-26,36019,7945983,63734,7198849,485,118952
218,2020-10-27,43034,7989017,58428,7257277,517,119469

In [19]:
data_daily["Date"][len(data_daily)-1]

Timestamp('2020-10-27 00:00:00')

In [20]:
data_daily.dtypes

Date               datetime64[ns]
Daily Confirmed             int64
Total Confirmed             int64
Daily Recovered             int64
Total Recovered             int64
Daily Deceased              int64
Total Deceased              int64
dtype: object

In [21]:
data_daily_ratio_with_two_precision=data_daily.copy()

In [22]:
new_cols=["Daily_Confirmed_Ratio","Total_Confirmed_Ratio","Daily_Recovered_Ratio","Total_Recovered_Ratio","Daily_Deceased_Ratio","Total_Deceased_Ratio"]
existing_cols=list(data_daily_ratio_with_two_precision.columns)
existing_cols.pop(0)
existing_cols
for i,j in zip(new_cols,existing_cols):
    data_daily_ratio_with_two_precision[i]=list(range(len(data_daily_ratio_with_two_precision)))
    data_daily_ratio_with_two_precision[i][0]=1
    tmp=[]
    tmp.append(data_daily_ratio_with_two_precision[i][0])
    for k in range(0,len(data_daily_ratio_with_two_precision)-1):
        tmp.append(round(data_daily_ratio_with_two_precision[j][k+1]/data_daily_ratio_with_two_precision[j][k],2))
    data_daily_ratio_with_two_precision[i]=tmp
data_daily_ratio_with_two_precision.head()

<ipython-input-22-f5761363647c>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily_ratio_with_two_precision[i][0]=1

,Date,Daily Confirmed,Total Confirmed,Daily Recovered,Total Recovered,Daily Deceased,Total Deceased,Daily_Confirmed_Ratio,Total_Confirmed_Ratio,Daily_Recovered_Ratio,Total_Recovered_Ratio,Daily_Deceased_Ratio,Total_Deceased_Ratio
0,2020-03-23,94,497,2,25,2,9,1.00,1.00,1.00,1.00,1.0,1.00
1,2020-03-24,74,571,15,40,1,10,0.79,1.15,7.50,1.60,0.5,1.11
2,2020-03-25,86,657,3,43,1,11,1.16,1.15,0.20,1.08,1.0,1.10
3,2020-03-26,73,730,7,50,5,16,0.85,1.11,2.33,1.16,5.0,1.45
4,2020-03-27,153,883,25,75,3,19,2.10,1.21,3.57,1.50,0.6,1.19

In [23]:
data_daily_ratio=data_daily.copy()

In [24]:
new_cols=["Daily_Confirmed_Ratio","Total_Confirmed_Ratio","Daily_Recovered_Ratio","Total_Recovered_Ratio","Daily_Deceased_Ratio","Total_Deceased_Ratio"]
existing_cols=list(data_daily_ratio.columns)
existing_cols.pop(0)
existing_cols
for i,j in zip(new_cols,existing_cols):
    data_daily_ratio[i]=list(range(len(data_daily_ratio)))
    data_daily_ratio[i][0]=1
    tmp=[]
    tmp.append(data_daily_ratio[i][0])
    for k in range(0,len(data_daily_ratio)-1):
        tmp.append(data_daily_ratio[j][k+1]/data_daily_ratio[j][k])
    data_daily_ratio[i]=tmp
data_daily_ratio.head()

<ipython-input-24-d765217f50de>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_daily_ratio[i][0]=1

,Date,Daily Confirmed,Total Confirmed,Daily Recovered,Total Recovered,Daily Deceased,Total Deceased,Daily_Confirmed_Ratio,Total_Confirmed_Ratio,Daily_Recovered_Ratio,Total_Recovered_Ratio,Daily_Deceased_Ratio,Total_Deceased_Ratio
0,2020-03-23,94,497,2,25,2,9,1.000000,1.000000,1.000000,1.000000,1.0,1.000000
1,2020-03-24,74,571,15,40,1,10,0.787234,1.148893,7.500000,1.600000,0.5,1.111111
2,2020-03-25,86,657,3,43,1,11,1.162162,1.150613,0.200000,1.075000,1.0,1.100000
3,2020-03-26,73,730,7,50,5,16,0.848837,1.111111,2.333333,1.162791,5.0,1.454545
4,2020-03-27,153,883,25,75,3,19,2.095890,1.209589,3.571429,1.500000,0.6,1.187500

In [25]:
strt_cnt=1
end_cnt=8
strt_lst=[]
end_lst=[]
strt_lst.append(strt_cnt)
end_lst.append(end_cnt)
while(end_cnt<=len(data_daily_ratio)):
        strt_cnt+=1
        strt_lst.append(strt_cnt)
        end_cnt+=1
        end_lst.append(end_cnt)
if(end_lst[len(end_lst)-1]>=len(data_daily_ratio)):
    end_lst.pop(len(end_lst)-1)
strt_lst.pop(len(strt_lst)-1)
#print(strt_lst)
#print(end_lst)
#print(len(strt_lst)==len(end_lst))

for st,en in zip(strt_lst,end_lst):

    dcr=data_daily_ratio.iloc[st:en,7:8]
    dcr.reset_index(inplace = True, drop = True)
    dc=data_daily_ratio.iloc[st:en,1:2]
    dc.reset_index(inplace = True, drop = True)



    next_day_confirmed_case_count_mean_based=dcr.mean()[0]*dc.mean()[0]

    next_day_confirmed_case_count_max_based=max(dcr["Daily_Confirmed_Ratio"])*max(dc["Daily Confirmed"])


    next_day_confirmed_case_count_mean_max_based=dcr.mean()[0]*max(dc["Daily Confirmed"])


    next_day_confirmed_case_count_max_mean_based=max(dcr["Daily_Confirmed_Ratio"])*dc.mean()[0]


    next_day_confirmed_case_count_mean_last_based=dcr.mean()[0]*dc["Daily Confirmed"][len(dc)-1]


    next_day_confirmed_case_count_last_mean_based=dcr["Daily_Confirmed_Ratio"][len(dcr)-1]*dc.mean()[0]


    next_day_confirmed_case_count_last_based=dcr["Daily_Confirmed_Ratio"][len(dcr)-1]*dc["Daily Confirmed"][len(dc)-1]


    next_day_confirmed_case_count_middle_based=dcr["Daily_Confirmed_Ratio"][3]*dc["Daily Confirmed"][3]


    pred_val=[]
    pred_val.append(np.round(next_day_confirmed_case_count_mean_based))
    pred_val.append(np.round(next_day_confirmed_case_count_max_based))
    pred_val.append(np.round(next_day_confirmed_case_count_mean_max_based))
    pred_val.append(np.round(next_day_confirmed_case_count_max_mean_based))
    pred_val.append(np.round(next_day_confirmed_case_count_mean_last_based))
    pred_val.append(np.round(next_day_confirmed_case_count_last_mean_based))
    pred_val.append(np.round(next_day_confirmed_case_count_last_based))
    pred_val.append(np.round(next_day_confirmed_case_count_middle_based))

    if(en<len(data_daily_ratio)):
        pred_dict={"date":data_daily_ratio["Date"][en-1]+datetime.timedelta(hours=24),"original_val":data_daily_ratio["Daily Confirmed"][en],"mean_based":pred_val[0],"max_based":pred_val[1],"mean_max_based":pred_val[2],"max_mean_based":pred_val[3],"mean_last_based":pred_val[4],"last_mean_based":pred_val[5],"last_based":pred_val[6],"middle_based":pred_val[7]}
    else:
        pred_dict={"date":data_daily_ratio["Date"][en-1]+datetime.timedelta(hours=24),"original_val":0,"mean_based":pred_val[0],"max_based":pred_val[1],"mean_max_based":pred_val[2],"max_mean_based":pred_val[3],"mean_last_based":pred_val[4],"last_mean_based":pred_val[5],"last_based":pred_val[6],"middle_based":pred_val[7]}
   
    pred_df=pd.DataFrame(pred_dict, index=[0])
    
    
    
d=pd.read_excel(r"C:\Users\Mark 1\amprd_df_strd.xlsx")
d=pd.concat([d,pred_df])
d.reset_index(drop=True,inplace=True)
d['original_val'][len(d)-2]=data_daily_ratio['Daily Confirmed'][len(data_daily_ratio)-1]
d.to_excel("amprd_df_strd.xlsx",index=False)

<ipython-input-25-7492d62499ab>:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d['original_val'][len(d)-2]=data_daily_ratio['Daily Confirmed'][len(data_daily_ratio)-1]

In [26]:
dc=pd.read_excel(r"C:\Users\Mark 1\amprd_df_strd.xlsx")
dc = dc.loc[:, ~dc.columns.str.contains('^Unnamed')]
dc.tail()

,date,original_val,mean_based,max_based,mean_max_based,max_mean_based,mean_last_based,last_mean_based,last_based,middle_based
206,2020-10-24,50366,53905,73919,61005,65317,53157,54248,53495,64908
207,2020-10-25,45922,51831,67501,55227,63350,49215,49537,47037,58248
208,2020-10-26,36019,50342,67196,54967,61542,44863,46983,41870,52542
209,2020-10-27,43034,48869,67196,54800,59924,35082,39354,28252,53495
210,2020-10-28,0,47298,67222,54803,58015,41917,58015,51415,47037

In [27]:
dce=dc.copy()

In [28]:
strt_cnt=1
end_cnt=8
strt_lst=[]
end_lst=[]
strt_lst.append(strt_cnt)
end_lst.append(end_cnt)
while(end_cnt<=len(data_daily_ratio)):
        strt_cnt+=1
        strt_lst.append(strt_cnt)
        end_cnt+=1
        end_lst.append(end_cnt)
if(end_lst[len(end_lst)-1]>=len(data_daily_ratio)):
    end_lst.pop(len(end_lst)-1)
strt_lst.pop(len(strt_lst)-1)
#print(strt_lst)
#print(end_lst)
#print(len(strt_lst)==len(end_lst))
#print(len(strt_lst))
#print(len(end_lst))

213

In [29]:
colls=list(dc.columns)
colls.pop(0)
colls.pop(0)
collss=["mb","mxb","memb","mxmb","mlb","lmb","lb","mdb"]
for i in collss:
    dce[i]=pd.Series(range(1,len(dce)+1))
colls

['mean_based',
 'max_based',
 'mean_max_based',
 'max_mean_based',
 'mean_last_based',
 'last_mean_based',
 'last_based',
 'middle_based']

In [30]:
for i,j in zip(colls,collss):
    for k in range(len(dce)):
        dce[j][k]=dce["original_val"][k]-dce[i][k]
dce

<ipython-input-30-e3d4143616d2>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dce[j][k]=dce["original_val"][k]-dce[i][k]

,date,original_val,mean_based,max_based,mean_max_based,max_mean_based,mean_last_based,last_mean_based,last_based,middle_based,mb,mxb,memb,mxmb,mlb,lmb,lb,mdb
0,2020-03-31,309,139,392,220,248,220,185,291,321,170,-83,89,61,89,124,18,-12
1,2020-04-01,424,197,648,401,319,401,251,511,121,227,-224,23,105,23,173,-87,303
2,2020-04-02,486,266,889,563,420,563,275,582,106,220,-403,-77,66,-77,211,-96,380
3,2020-04-03,560,355,1019,666,543,666,297,557,291,205,-459,-106,17,-106,263,3,269
4,2020-04-04,579,392,925,692,525,692,366,645,511,187,-346,-113,54,-113,213,-66,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,2020-10-24,50366,53905,73919,61005,65317,53157,54248,53495,64908,-3539,-23553,-10639,-14951,-2791,-3882,-3129,-14542
207,2020-10-25,45922,51831,67501,55227,63350,49215,49537,47037,58248,-5909,-21579,-9305,-17428,-3293,-3615,-1115,-12326
208,2020-10-26,36019,50342,67196,54967,61542,44863,46983,41870,52542,-14323,-31177,-18948,-25523,-8844,-10964,-5851,-16523
209,2020-10-27,43034,48869,67196,54800,59924,35082,39354,28252,53495,-5835,-24162,-11766,-16890,7952,3680,14782,-10461
210,2020-10-28,0,47298,67222,54803,58015,41917,58015,51415,47037,-47298,-67222,-54803,-58015,-41917,-58015,-51415,-47037

In [31]:
dce.to_excel("amerrprd_df_strd.xlsx")
dce=pd.read_excel(r"C:\Users\Mark 1\amerrprd_df_strd.xlsx")
dce = dce.loc[:, ~dce.columns.str.contains('^Unnamed')]
dce.to_excel("amerrprd_df_strd.xlsx")

In [32]:
edf=dce.iloc[0:len(dce),10:]
edf

        mb    mxb   memb   mxmb    mlb    lmb     lb    mdb
0      170    -83     89     61     89    124     18    -12
1      227   -224     23    105     23    173    -87    303
2      220   -403    -77     66    -77    211    -96    380
3      205   -459   -106     17   -106    263      3    269
4      187   -346   -113     54   -113    213    -66     68
..     ...    ...    ...    ...    ...    ...    ...    ...
206  -3539 -23553 -10639 -14951  -2791  -3882  -3129 -14542
207  -5909 -21579  -9305 -17428  -3293  -3615  -1115 -12326
208 -14323 -31177 -18948 -25523  -8844 -10964  -5851 -16523
209  -5835 -24162 -11766 -16890   7952   3680  14782 -10461
210 -47298 -67222 -54803 -58015 -41917 -58015 -51415 -47037

[211 rows x 8 columns]

In [33]:

for j,k in zip(range(len(edf)),range(len(dce)-1)):
    
    a=list(edf.loc[j])
    pos=[]
    neg=[]
    for i in a:
        if(i>=0):
            pos.append(i)
        else:
            neg.append(i)
    if(len(pos)):
        ps=min(pos)
        psi=a.index(ps)
        psc=list(edf.columns)[psi]
    if(len(neg)):
        ng=max(neg)
        ngi=a.index(ng)
        ngc=list(edf.columns)[ngi]
    
    
    print("for date: "+str(dce["date"][k]).strip("00:00:00")+" the lowest positve error was by the method: "+psc+" and the highest negative error by the method: "+ngc)

for date: 2020-03-31  the lowest positve error was by the method: lb and the highest negative error by the method: mdb
for date: 2020-04-01  the lowest positve error was by the method: memb and the highest negative error by the method: lb
for date: 2020-04-02  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-04-03  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-04-04  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-04-05  the lowest positve error was by the method: lb and the highest negative error by the method: mxmb
for date: 2020-04-06  the lowest positve error was by the method: lmb and the highest negative error by the method: mdb
for date: 2020-04-07  the lowest positve error was by the method: mlb and the highest negative error by the method: mb
for date: 2020-04-08  the lowest positve error was by the method: mlb and the highest negative error by the method: mb
for date: 2020-04-09  the lowest positve error was by the method: mxb and the highest negative error by the method: mb
for date: 2020-04-10  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-04-11  the lowest positve error was by the method: mb and the highest negative error by the method: mxmb
for date: 2020-04-12  the lowest positve error was by the method: mb and the highest negative error by the method: lb
for date: 2020-04-13  the lowest positve error was by the method: mdb and the highest negative error by the method: mxb
for date: 2020-04-14  the lowest positve error was by the method: mb and the highest negative error by the method: mxmb
for date: 2020-04-15  the lowest positve error was by the method: lb and the highest negative error by the method: mb
for date: 2020-04-16  the lowest positve error was by the method: mb and the highest negative error by the method: memb
for date: 2020-04-17  the lowest positve error was by the method: mb and the highest negative error by the method: mb
for date: 2020-04-18  the lowest positve error was by the method: memb and the highest negative error by the method: mxmb
for date: 2020-04-19  the lowest positve error was by the method: lmb and the highest negative error by the method: mxmb
for date: 2020-04-20  the lowest positve error was by the method: lmb and the highest negative error by the method: mdb
for date: 2020-04-21  the lowest positve error was by the method: mlb and the highest negative error by the method: memb
for date: 2020-04-22  the lowest positve error was by the method: mlb and the highest negative error by the method: mb
for date: 2020-04-23  the lowest positve error was by the method: mlb and the highest negative error by the method: memb
for date: 2020-04-24  the lowest positve error was by the method: mdb and the highest negative error by the method: mb
for date: 2020-04-25  the lowest positve error was by the method: memb and the highest negative error by the method: mdb
for date: 2020-04-26  the lowest positve error was by the method: mb and the highest negative error by the method: memb
for date: 2020-04-27  the lowest positve error was by the method: mb and the highest negative error by the method: mlb
for date: 2020-04-28  the lowest positve error was by the method: mlb and the highest negative error by the method: memb
for date: 2020-04-29  the lowest positve error was by the method: mb and the highest negative error by the method: lmb
for date: 2020-04-30  the lowest positve error was by the method: mb and the highest negative error by the method: mlb
for date: 2020-05-01  the lowest positve error was by the method: mxmb and the highest negative error by the method: mxb
for date: 2020-05-02  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-05-03  the lowest positve error was by the method: lb and the highest negative error by the method: mxb
for date: 2020-05-04  the lowest positve error was by the method: lb and the highest negative error by the method: mxb
for date: 2020-05-05  the lowest positve error was by the method: mb and the highest negative error by the method: lmb
for date: 2020-05-06  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-05-07  the lowest positve error was by the method: mb and the highest negative error by the method: mdb
for date: 2020-05-08  the lowest positve error was by the method: lb and the highest negative error by the method: mb
for date: 2020-05-09  the lowest positve error was by the method: mdb and the highest negative error by the method: lmb
for date: 2020-05-10  the lowest positve error was by the method: mxmb and the highest negative error by the method: mdb
for date: 2020-05-11  the lowest positve error was by the method: mdb and the highest negative error by the method: mb
for date: 2020-05-12  the lowest positve error was by the method: mb and the highest negative error by the method: mlb
for date: 2020-05-13  the lowest positve error was by the method: mlb and the highest negative error by the method: memb
for date: 2020-05-14  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-05-15  the lowest positve error was by the method: mb and the highest negative error by the method: lmb
for date: 2020-05-16  the lowest positve error was by the method: memb and the highest negative error by the method: mxmb
for date: 2020-05-17  the lowest positve error was by the method: lmb and the highest negative error by the method: memb
for date: 2020-05-18  the lowest positve error was by the method: lmb and the highest negative error by the method: mxmb
for date: 2020-05-19  the lowest positve error was by the method: mxmb and the highest negative error by the method: mxb
for date: 2020-05-20  the lowest positve error was by the method: mb and the highest negative error by the method: mdb
for date: 2020-05-21  the lowest positve error was by the method: mdb and the highest negative error by the method: mlb
for date: 2020-05-22  the lowest positve error was by the method: mlb and the highest negative error by the method: memb
for date: 2020-05-23  the lowest positve error was by the method: mb and the highest negative error by the method: lb
for date: 2020-05-24  the lowest positve error was by the method: memb and the highest negative error by the method: mxmb
for date: 2020-05-25  the lowest positve error was by the method: mdb and the highest negative error by the method: mb
for date: 2020-05-26  the lowest positve error was by the method: lb and the highest negative error by the method: mb
for date: 2020-05-27  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-05-28  the lowest positve error was by the method: mb and the highest negative error by the method: memb
for date: 2020-05-29  the lowest positve error was by the method: memb and the highest negative error by the method: mxmb
for date: 2020-05-30  the lowest positve error was by the method: lmb and the highest negative error by the method: memb
for date: 2020-05-31  the lowest positve error was by the method: memb and the highest negative error by the method: mxmb
for date: 2020-06-01  the lowest positve error was by the method: mb and the highest negative error by the method: lmb
for date: 2020-06-02  the lowest positve error was by the method: mlb and the highest negative error by the method: memb
for date: 2020-06-03  the lowest positve error was by the method: memb and the highest negative error by the method: mxmb
for date: 2020-06-04  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-06-05  the lowest positve error was by the method: mb and the highest negative error by the method: mxmb
for date: 2020-06-06  the lowest positve error was by the method: mxmb and the highest negative error by the method: mxb
for date: 2020-06-07  the lowest positve error was by the method: memb and the highest negative error by the method: lb
for date: 2020-06-08  the lowest positve error was by the method: memb and the highest negative error by the method: mb
for date: 2020-06-09  the lowest positve error was by the method: mb and the highest negative error by the method: mxmb
for date: 2020-06-10  the lowest positve error was by the method: memb and the highest negative error by the method: mdb
for date: 2020-06-11  the lowest positve error was by the method: mb and the highest negative error by the method: lmb
for date: 2020-06-12  the lowest positve error was by the method: lb and the highest negative error by the method: mlb
for date: 2020-06-13  the lowest positve error was by the method: memb and the highest negative error by the method: mxmb
for date: 2020-06-14  the lowest positve error was by the method: mb and the highest negative error by the method: lmb
for date: 2020-06-15  the lowest positve error was by the method: mb and the highest negative error by the method: lmb
for date: 2020-06-16  the lowest positve error was by the method: mlb and the highest negative error by the method: mb
for date: 2020-06-17  the lowest positve error was by the method: mdb and the highest negative error by the method: mxb
for date: 2020-06-18  the lowest positve error was by the method: mxmb and the highest negative error by the method: mxb
for date: 2020-06-19  the lowest positve error was by the method: lb and the highest negative error by the method: mxb
for date: 2020-06-20  the lowest positve error was by the method: lb and the highest negative error by the method: mxb
for date: 2020-06-21  the lowest positve error was by the method: lmb and the highest negative error by the method: mxmb
for date: 2020-06-22  the lowest positve error was by the method: lmb and the highest negative error by the method: mb
for date: 2020-06-23  the lowest positve error was by the method: mb and the highest negative error by the method: mdb
for date: 2020-06-24  the lowest positve error was by the method: lmb and the highest negative error by the method: mdb
for date: 2020-06-25  the lowest positve error was by the method: lb and the highest negative error by the method: mxb
for date: 2020-06-26  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-06-27  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-06-28  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-06-29  the lowest positve error was by the method: mb and the highest negative error by the method: lb
for date: 2020-06-30  the lowest positve error was by the method: lb and the highest negative error by the method: mdb
for date: 2020-07-01  the lowest positve error was by the method: mb and the highest negative error by the method: mxmb
for date: 2020-07-02  the lowest positve error was by the method: mxmb and the highest negative error by the method: mxb
for date: 2020-07-03  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-07-04  the lowest positve error was by the method: lb and the highest negative error by the method: mxb
for date: 2020-07-05  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-07-06  the lowest positve error was by the method: mb and the highest negative error by the method: lb
for date: 2020-07-07  the lowest positve error was by the method: mb and the highest negative error by the method: mlb
for date: 2020-07-08  the lowest positve error was by the method: mxmb and the highest negative error by the method: mxb
for date: 2020-07-09  the lowest positve error was by the method: mb and the highest negative error by the method: lmb
for date: 2020-07-10  the lowest positve error was by the method: mxmb and the highest negative error by the method: mxb
for date: 2020-07-11  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-07-12  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-07-13  the lowest positve error was by the method: lmb and the highest negative error by the method: mxmb
for date: 2020-07-14  the lowest positve error was by the method: mdb and the highest negative error by the method: memb
for date: 2020-07-15  the lowest positve error was by the method: lb and the highest negative error by the method: mxb
for date: 2020-07-16  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-07-17  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-07-18  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-07-19  the lowest positve error was by the method: lb and the highest negative error by the method: mxb
for date: 2020-07-20  the lowest positve error was by the method: lmb and the highest negative error by the method: mxmb
for date: 2020-07-21  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-07-22  the lowest positve error was by the method: mxb and the highest negative error by the method: memb
for date: 2020-07-23  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-07-24  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-07-25  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-07-26  the lowest positve error was by the method: mb and the highest negative error by the method: lb
for date: 2020-07-27  the lowest positve error was by the method: lmb and the highest negative error by the method: mb
for date: 2020-07-28  the lowest positve error was by the method: mdb and the highest negative error by the method: memb
for date: 2020-07-29  the lowest positve error was by the method: memb and the highest negative error by the method: lb
for date: 2020-07-30  the lowest positve error was by the method: memb and the highest negative error by the method: lb
for date: 2020-07-31  the lowest positve error was by the method: memb and the highest negative error by the method: lb
for date: 2020-08-01  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-08-02  the lowest positve error was by the method: lmb and the highest negative error by the method: lb
for date: 2020-08-03  the lowest positve error was by the method: lmb and the highest negative error by the method: mlb
for date: 2020-08-04  the lowest positve error was by the method: mlb and the highest negative error by the method: mb
for date: 2020-08-05  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-08-06  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-08-07  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-08-08  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-08-09  the lowest positve error was by the method: lmb and the highest negative error by the method: mdb
for date: 2020-08-10  the lowest positve error was by the method: lmb and the highest negative error by the method: lmb
for date: 2020-08-11  the lowest positve error was by the method: mdb and the highest negative error by the method: mxmb
for date: 2020-08-12  the lowest positve error was by the method: mlb and the highest negative error by the method: memb
for date: 2020-08-13  the lowest positve error was by the method: mb and the highest negative error by the method: lmb
for date: 2020-08-14  the lowest positve error was by the method: mlb and the highest negative error by the method: memb
for date: 2020-08-15  the lowest positve error was by the method: mb and the highest negative error by the method: lmb
for date: 2020-08-16  the lowest positve error was by the method: mb and the highest negative error by the method: lmb
for date: 2020-08-17  the lowest positve error was by the method: lb and the highest negative error by the method: lmb
for date: 2020-08-18  the lowest positve error was by the method: mb and the highest negative error by the method: mdb
for date: 2020-08-19  the lowest positve error was by the method: memb and the highest negative error by the method: mxmb
for date: 2020-08-20  the lowest positve error was by the method: lmb and the highest negative error by the method: memb
for date: 2020-08-21  the lowest positve error was by the method: lb and the highest negative error by the method: mlb
for date: 2020-08-22  the lowest positve error was by the method: memb and the highest negative error by the method: mxmb
for date: 2020-08-23  the lowest positve error was by the method: memb and the highest negative error by the method: lmb
for date: 2020-08-24  the lowest positve error was by the method: lmb and the highest negative error by the method: mlb
for date: 2020-08-25  the lowest positve error was by the method: lmb and the highest negative error by the method: mb
for date: 2020-08-26  the lowest positve error was by the method: lb and the highest negative error by the method: mxb
for date: 2020-08-27  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-08-28  the lowest positve error was by the method: mb and the highest negative error by the method: lb
for date: 2020-08-29  the lowest positve error was by the method: memb and the highest negative error by the method: mxmb
for date: 2020-08-30  the lowest positve error was by the method: lmb and the highest negative error by the method: memb
for date: 2020-08-31  the lowest positve error was by the method: lmb and the highest negative error by the method: lmb
for date: 2020-09-01  the lowest positve error was by the method: mb and the highest negative error by the method: memb
for date: 2020-09-02  the lowest positve error was by the method: memb and the highest negative error by the method: mxmb
for date: 2020-09-03  the lowest positve error was by the method: memb and the highest negative error by the method: lb
for date: 2020-09-04  the lowest positve error was by the method: memb and the highest negative error by the method: mxmb
for date: 2020-09-05  the lowest positve error was by the method: lb and the highest negative error by the method: mxmb
for date: 2020-09-06  the lowest positve error was by the method: mdb and the highest negative error by the method: memb
for date: 2020-09-07  the lowest positve error was by the method: mdb and the highest negative error by the method: lmb
for date: 2020-09-08  the lowest positve error was by the method: mb and the highest negative error by the method: mdb
for date: 2020-09-09  the lowest positve error was by the method: mdb and the highest negative error by the method: mxmb
for date: 2020-09-10  the lowest positve error was by the method: lmb and the highest negative error by the method: memb
for date: 2020-09-11  the lowest positve error was by the method: mb and the highest negative error by the method: lb
for date: 2020-09-12  the lowest positve error was by the method: mb and the highest negative error by the method: lb

In [34]:
err_dict={"date":[],"mipe":[],"mxne":[],"mipv":[],"mxnv":[],"original_val":[],"pprd_val":[],"nprd_val":[]}
psc=[]
ngc=[]
date=[]
ps=[]
ng=[]
org_val=[]
pprd_val=[]
nprd_val=[]
for j,k in zip(range(len(edf)),range(len(dce))):
    
    a=list(edf.loc[j])
    pos=[]
    neg=[]
    for i in a:
        if(i>=0):
            pos.append(i)
        else:
            neg.append(i)
    if(len(pos)):
        aa=min(pos)
    
        psi=a.index(aa)
    
        ps.append(aa)
    
        psc.append(list(edf.columns)[psi])
    
    
        pprd_val.append(dce["original_val"][k]-aa)
    else:
        ps.append("No")
    
        psc.append("No")
    
    
        pprd_val.append("No")
        
    
    if(len(neg)):
        bb=max(neg)
        ngi=a.index(bb)
        ng.append(bb)
        ngc.append(list(edf.columns)[ngi])
        nprd_val.append(dce["original_val"][k]-bb)
    else:
        ng.append("No")
    
        ngc.append("No")
    
    
        nprd_val.append("No")
    
    date.append(str(dce["date"][k]).strip("00:00:00"))
    org_val.append(dce["original_val"][k])
err_dict.update({"date":date})
err_dict.update({"mipe":psc})
err_dict.update({"mxne":ngc})
err_dict.update({"mipv":ps})
err_dict.update({"mxnv":ng})
err_dict.update({"original_val":org_val})
err_dict.update({"pprd_val":pprd_val})
err_dict.update({"nprd_val":nprd_val})

The history saving thread hit an unexpected error (OperationalError('database is locked')).History will not be written to the database.

In [35]:
err_dict

{'date': ['2020-03-31 ',
  '2020-04-01 ',
  '2020-04-02 ',
  '2020-04-03 ',
  '2020-04-04 ',
  '2020-04-05 ',
  '2020-04-06 ',
  '2020-04-07 ',
  '2020-04-08 ',
  '2020-04-09 ',
  '2020-04-10 ',
  '2020-04-11 ',
  '2020-04-12 ',
  '2020-04-13 ',
  '2020-04-14 ',
  '2020-04-15 ',
  '2020-04-16 ',
  '2020-04-17 ',
  '2020-04-18 ',
  '2020-04-19 ',
  '2020-04-20 ',
  '2020-04-21 ',
  '2020-04-22 ',
  '2020-04-23 ',
  '2020-04-24 ',
  '2020-04-25 ',
  '2020-04-26 ',
  '2020-04-27 ',
  '2020-04-28 ',
  '2020-04-29 ',
  '2020-04-30 ',
  '2020-05-01 ',
  '2020-05-02 ',
  '2020-05-03 ',
  '2020-05-04 ',
  '2020-05-05 ',
  '2020-05-06 ',
  '2020-05-07 ',
  '2020-05-08 ',
  '2020-05-09 ',
  '2020-05-10 ',
  '2020-05-11 ',
  '2020-05-12 ',
  '2020-05-13 ',
  '2020-05-14 ',
  '2020-05-15 ',
  '2020-05-16 ',
  '2020-05-17 ',
  '2020-05-18 ',
  '2020-05-19 ',
  '2020-05-20 ',
  '2020-05-21 ',
  '2020-05-22 ',
  '2020-05-23 ',
  '2020-05-24 ',
  '2020-05-25 ',
  '2020-05-26 ',
  '2020-05-27 ',
  '2020-05-28 ',
  '2020-05-29 ',
  '2020-05-30 ',
  '2020-05-31 ',
  '2020-06-01 ',
  '2020-06-02 ',
  '2020-06-03 ',
  '2020-06-04 ',
  '2020-06-05 ',
  '2020-06-06 ',
  '2020-06-07 ',
  '2020-06-08 ',
  '2020-06-09 ',
  '2020-06-10 ',
  '2020-06-11 ',
  '2020-06-12 ',
  '2020-06-13 ',
  '2020-06-14 ',
  '2020-06-15 ',
  '2020-06-16 ',
  '2020-06-17 ',
  '2020-06-18 ',
  '2020-06-19 ',
  '2020-06-20 ',
  '2020-06-21 ',
  '2020-06-22 ',
  '2020-06-23 ',
  '2020-06-24 ',
  '2020-06-25 ',
  '2020-06-26 ',
  '2020-06-27 ',
  '2020-06-28 ',
  '2020-06-29 ',
  '2020-06-30 ',
  '2020-07-01 ',
  '2020-07-02 ',
  '2020-07-03 ',
  '2020-07-04 ',
  '2020-07-05 ',
  '2020-07-06 ',
  '2020-07-07 ',
  '2020-07-08 ',
  '2020-07-09 ',
  '2020-07-10 ',
  '2020-07-11 ',
  '2020-07-12 ',
  '2020-07-13 ',
  '2020-07-14 ',
  '2020-07-15 ',
  '2020-07-16 ',
  '2020-07-17 ',
  '2020-07-18 ',
  '2020-07-19 ',
  '2020-07-20 ',
  '2020-07-21 ',
  '2020-07-22 ',
  '2020-07-23 ',
  '2020-07-24 ',
  '2020-07-25 ',
  '2020-07-26 ',
  '2020-07-27 ',
  '2020-07-28 ',
  '2020-07-29 ',
  '2020-07-30 ',
  '2020-07-31 ',
  '2020-08-01 ',
  '2020-08-02 ',
  '2020-08-03 ',
  '2020-08-04 ',
  '2020-08-05 ',
  '2020-08-06 ',
  '2020-08-07 ',
  '2020-08-08 ',
  '2020-08-09 ',
  '2020-08-10 ',
  '2020-08-11 ',
  '2020-08-12 ',
  '2020-08-13 ',
  '2020-08-14 ',
  '2020-08-15 ',
  '2020-08-16 ',
  '2020-08-17 ',
  '2020-08-18 ',
  '2020-08-19 ',
  '2020-08-20 ',
  '2020-08-21 ',
  '2020-08-22 ',
  '2020-08-23 ',
  '2020-08-24 ',
  '2020-08-25 ',
  '2020-08-26 ',
  '2020-08-27 ',
  '2020-08-28 ',
  '2020-08-29 ',
  '2020-08-30 ',
  '2020-08-31 ',
  '2020-09-01 ',
  '2020-09-02 ',
  '2020-09-03 ',
  '2020-09-04 ',
  '2020-09-05 ',
  '2020-09-06 ',
  '2020-09-07 ',
  '2020-09-08 ',
  '2020-09-09 ',
  '2020-09-10 ',
  '2020-09-11 ',
  '2020-09-12 ',
  '2020-09-13 ',
  '2020-09-14 ',
  '2020-09-15 ',
  '2020-09-16 ',
  '2020-09-17 ',
  '2020-09-18 ',
  '2020-09-19 ',
  '2020-09-20 ',
  '2020-09-21 ',
  '2020-09-22 ',
  '2020-09-23 ',
  '2020-09-24 ',
  '2020-09-25 ',
  '2020-09-26 ',
  '2020-09-27 ',
  '2020-09-28 ',
  '2020-09-29 ',
  '2020-09-30 ',
  '2020-10-01 ',
  '2020-10-02 ',
  '2020-10-03 ',
  '2020-10-04 ',
  '2020-10-05 ',
  '2020-10-06 ',
  '2020-10-07 ',
  '2020-10-08 ',
  '2020-10-09 ',
  '2020-10-10 ',
  '2020-10-11 ',
  '2020-10-12 ',
  '2020-10-13 ',
  '2020-10-14 ',
  '2020-10-15 ',
  '2020-10-16 ',
  '2020-10-17 ',
  '2020-10-18 ',
  '2020-10-19 ',
  '2020-10-20 ',
  '2020-10-21 ',
  '2020-10-22 ',
  '2020-10-24 ',
  '2020-10-25 ',
  '2020-10-26 ',
  '2020-10-27 ',
  '2020-10-28 '],
 'mipe': ['lb',
  'memb',
  'mxmb',
  'lb',
  'mxmb',
  'lb',
  'lmb',
  'mlb',
  'No',
  'mxb',
  'mxmb',
  'mb',
  'mb',
  'mdb',
  'mb',
  'lb',
  'mb',
  'No',
  'memb',
  'lmb',
  'No',
  'mlb',
  'No',
  'mlb',
  'mdb',
  'memb',
  'mb',
  'mb',
  'mlb',
  'mb',
  'mb',
  'mxmb',
  'mxmb',
  'lb',
  'lb',
  'mb',
  'mxmb',
  'mb',
  'lb',
  'mdb',
  'mxmb',
  'mdb',
  'mb',
  'mlb',
  'lb',
  'mb',
  'memb',
  'lmb',
  'lmb',
  'mxmb',
  'mb',
  'mdb',
  'mlb',
  'mb',
  'memb',
  'mdb',
  'lb',
  'memb',
  'mb',
  'memb',
  'lmb',
  'memb',
  'mb',
  'mlb',
  'memb',
  'mxmb',
  'mb',
  'mxmb',
  'memb',
  'No',
  'mb',
  'memb',
  'mb',
  'lb',
  'memb',
  'mb',
  'No',
  'mlb',
  'mdb',
  'mxmb',
  'lb',
  'lb',
  'lmb',
  'lmb',
  'mb',
  'lmb',
  'lb',
  'mxmb',
  'memb',
  'mxmb',
  'mb',
  'lb',
  'mb',
  'mxmb',
  'memb',
  'lb',
  'mxmb',
  'mb',
  'mb',
  'mxmb',
  'mb',
  'mxmb',
  'mxmb',
  'memb',
  'lmb',
  'mdb',
  'lb',
  'memb',
  'mxmb',
  'memb',
  'lb',
  'lmb',
  'mxmb',
  'mxb',
  'memb',
  'mxmb',
  'lb',
  'mb',
  'lmb',
  'mdb',
  'memb',
  'memb',
  'memb',
  'mxmb',
  'lmb',
  'lmb',
  'mlb',
  'mxmb',
  'mxmb',
  'mxmb',
  'memb',
  'lmb',
  'No',
  'mdb',
  'mlb',
  'mb',
  'mlb',
  'mb',
  'No',
  'lb',
  'mb',
  'memb',
  'lmb',
  'lb',
  'memb',
  'No',
  'lmb',
  'lmb',
  'lb',
  'mxmb',
  'mb',
  'memb',
  'lmb',
  'No',
  'mb',
  'memb',
  'memb',
  'memb',
  'lb',
  'mdb',
  'No',
  'mb',
  'mdb',
  'lmb',
  'mb',
  'mb',
  'mb',
  'No',
  'mlb',
  'mb',
  'mb',
  'lmb',
  'mlb',
  'No',
  'No',
  'lmb',
  'mlb',
  'mlb',
  'lmb',
  'lb',
  'No',
  'No',
  'lmb',
  'mb',
  'mdb',
  'lmb',
  'No',
  'mlb',
  'No',
  'lmb',
  'mb',
  'No',
  'mb',
  'mlb',
  'No',
  'No',
  'lmb',
  'mlb',
  'mdb',
  'lmb',
  'mlb',
  'No',
  'No',
  'lmb',
  'mlb',
  'mdb',
  'No',
  'No',
  'No',
  'lmb',
  'No'],
 'mxne': ['mdb',
  'lb',
  'memb',
  'memb',
  'lb',
  'mxmb',
  'mdb',
  'mb',
  'mb',
  'No',
  'memb',
  'mxmb',
  'lb',
  'mxb',
  'mxmb',
  'mb',
  'memb',
  'mb',
  'mxmb',
  'mxmb',
  'mdb',
  'memb',
  'mb',
  'memb',
  'mb',
  'mdb',
  'memb',
  'mlb',
  'memb',
  'lmb',
  'mlb',
  'mxb',
  'memb',
  'mxb',
  'mxb',
  'lmb',
  'memb',
  'mdb',
  'mb',
  'lmb',
  'mdb',
  'mb',
  'mlb',
  'memb',
  'memb',
  'lmb',
  'mxmb',
  'memb',
  'mxmb',
  'mxb',
  'mdb',
  'mlb',
  'memb',
  'lb',
  'mxmb',
  'mb',
  'mb',
  'mxb',
  'memb',
  'mxmb',
  'memb',
  'mxmb',
  'lmb',
  'memb',
  'mxmb',
  'memb',
  'mxmb',
  'mxb',
  'lb',
  'mb',
  'mxmb',
  'mdb',
  'lmb',
  'mlb',
  'mxmb',
  'lmb',
  'lmb',
  'mb',
  'mxb',
  'mxb',
  'mxb',
  'mxb',
  'mxmb',
  'mb',
  'mdb',
  'mdb',
  'mxb',
  'memb',
  'mxb',
  'memb',
  'lb',
  'mdb',
  'mxmb',
  'mxb',
  'mxb',
  'mxb',
  'memb',
  'lb',
  'mlb',
  'mxb',
  'lmb',
  'mxb',
  'memb',
  'mxb',
  'mxmb',
  'memb',
  'mxb',
  'mxb',
  'memb',
  'mxb',
  'mxb',
  'mxmb',
  'memb',
  'No',
  'mxb',
  'memb',
  'memb',
  'lb',
  'mb',
  'memb',
  'lb',
  'lb',
  'lb',
  'memb',
  'lb',
  'mlb',
  'mb',
  'memb',
  'lb',
  'memb',
  'mxb',
  'mdb',
  'lmb',
  'mxmb',
  'memb',
  'lmb',
  'memb',
  'lmb',
  'lmb',
  'lmb',
  'mdb',
  'mxmb',
  'memb',
  'mlb',
  'mxmb',
  'lmb',
  'mlb',
  'mb',
  'mxb',
  'memb',
  'lb',
  'mxmb',
  'memb',
  'lmb',
  'memb',
  'mxmb',
  'lb',
  'mxmb',
  'mxmb',
  'memb',
  'lmb',
  'mdb',
  'mxmb',
  'memb',
  'lb',
  'lb',
  'mlb',
  'lmb',
  'mb',
  'memb',
  'memb',
  'mb',
  'memb',
  'lmb',
  'lb',
  'mdb',
  'mb',
  'mb',
  'memb',
  'memb',
  'mb',
  'lb',
  'mb',
  'memb',
  'mb',
  'mlb',
  'lb',
  'lmb',
  'mlb',
  'mb',
  'lb',
  'mdb',
  'memb',
  'lmb',
  'mb',
  'lb',
  'mb',
  'mb',
  'mb',
  'mlb',
  'lmb',
  'mlb',
  'lb',
  'mb',
  'mb',
  'mlb',
  'mlb',
  'lb',
  'lb',
  'mb',
  'mlb'],
 'mipv': [18,
  23,
  66,
  3,
  54,
  10,
  10,
  6,
  'No',
  92,
  11,
  161,
  27,
  73,
  82,
  31,
  46,
  'No',
  81,
  35,
  'No',
  266,
  'No',
  270,
  436,
  16,
  0,
  17,
  251,
  15,
  35,
  194,
  129,
  208,
  257,
  215,
  172,
  140,
  235,
  761,
  235,
  488,
  39,
  25,
  93,
  6,
  357,
  52,
  337,
  838,
  714,
  705,
  87,
  612,
  75,
  72,
  122,
  158,
  439,
  653,
  553,
  106,
  11,
  838,
  313,
  268,
  285,
  188,
  107,
  'No',
  114,
  1,
  816,
  192,
  363,
  387,
  'No',
  778,
  288,
  297,
  150,
  207,
  1248,
  797,
  1077,
  51,
  31,
  96,
  1259,
  174,
  154,
  1106,
  462,
  1103,
  131,
  502,
  653,
  616,
  636,
  113,
  1410,
  1310,
  509,
  730,
  971,
  32,
  844,
  1680,
  1999,
  739,
  40,
  142,
  670,
  1748,
  480,
  1907,
  735,
  2774,
  2102,
  294,
  584,
  1379,
  1473,
  199,
  2665,
  134,
  136,
  57,
  2442,
  591,
  2282,
  1556,
  'No',
  504,
  3950,
  596,
  899,
  499,
  'No',
  1550,
  2540,
  1272,
  1575,
  1182,
  108,
  'No',
  2050,
  2891,
  1082,
  212,
  6698,
  242,
  6879,
  'No',
  1662,
  1315,
  27,
  1614,
  422,
  3891,
  'No',
  4203,
  1312,
  3502,
  5847,
  1399,
  605,
  'No',
  7828,
  4515,
  2962,
  718,
  15,
  'No',
  'No',
  6261,
  4114,
  445,
  291,
  3246,
  'No',
  'No',
  10409,
  3958,
  4599,
  2313,
  'No',
  674,
  'No',
  9912,
  3736,
  'No',
  1176,
  1477,
  'No',
  'No',
  7347,
  4949,
  1691,
  189,
  635,
  'No',
  'No',
  5902,
  2786,
  2319,
  'No',
  'No',
  'No',
  3680,
  'No'],
 'mxnv': [-12,
  -87,
  -77,
  -106,
  -66,
  -20,
  -73,
  -5,
  -21,
  'No',
  -17,
  -70,
  -79,
  -10,
  -299,
  -95,
  -308,
  -99,
  -211,
  -124,
  -32,
  -83,
  -40,
  -42,
  -95,
  -72,
  -348,
  -80,
  -30,
  -250,
  -1,
  -83,
  -55,
  -459,
  -271,
  -32,
  -344,
  -55,
  -56,
  -24,
  -56,
  -142,
  -78,
  -753,
  -386,
  -124,
  -281,
  -96,
  -502,
  -202,
  -315,
  -116,
  -53,
  -426,
  -635,
  -56,
  -820,
  -471,
  -276,
  -122,
  -75,
  -49,
  -100,
  -263,
  -182,
  -286,
  -530,
  -827,
  -554,
  -1341,
  -1045,
  -280,
  -87,
  -109,
  -222,
  -9,
  -194,
  -224,
  -348,
  -1670,
  -1611,
  -1510,
  -71,
  -462,
  -55,
  -322,
  -1270,
  -740,
  -935,
  -1292,
  -753,
  -49,
  -1011,
  -277,
  -2073,
  -1644,
  -729,
  -1366,
  -55,
  -1570,
  -56,
  -718,
  -847,
  -1551,
  -474,
  -166,
  -430,
  -71,
  -2332,
  -1246,
  -540,
  -350,
  -2708,
  'No',
  -4645,
  -1888,
  -1362,
  -2353,
  -334,
  -2239,
  -512,
  -522,
  -89,
  -3763,
  -174,
  -2806,
  -2676,
  -1183,
  -357,
  -1928,
  -3493,
  -410,
  -2727,
  -3710,
  -73,
  -3467,
  -2052,
  -71,
  -2814,
  -1887,
  -2089,
  -5774,
  -1259,
  -396,
  -6601,
  -4116,
  -2850,
  -467,
  -2496,
  -442,
  -1011,
  -723,
  -556,
  -5580,
  -3189,
  -3913,
  -3678,
  -1963,
  -176,
  -1017,
  -9361,
  -323,
  -7362,
  -1259,
  -349,
  -4142,
  -2275,
  -8706,
  -3204,
  -218,
  -1650,
  -538,
  -4851,
  -4555,
  -8013,
  -5947,
  -1817,
  -592,
  -5966,
  -3020,
  -1606,
  -7516,
  -2266,
  -1933,
  -1457,
  -1705,
  -2547,
  -392,
  -13890,
  -3988,
  -7091,
  -3271,
  -5512,
  -304,
  -4591,
  -7489,
  -6178,
  -460,
  -3027,
  -559,
  -1763,
  -5628,
  -3431,
  -4686,
  -1626,
  -1199,
  -2791,
  -1115,
  -5851,
  -5835,
  -41917],
 'original_val': [309,
  424,
  486,
  560,
  579,
  609,
  484,
  573,
  565,
  813,
  871,
  854,
  758,
  1243,
  1031,
  886,
  1061,
  922,
  1371,
  1580,
  1239,
  1537,
  1292,
  1667,
  1408,
  1835,
  1607,
  1568,
  1902,
  1705,
  1801,
  2396,
  2564,
  2952,
  3656,
  2971,
  3602,
  3344,
  3339,
  3175,
  4311,
  3592,
  3562,
  3726,
  3991,
  3808,
  4794,
  5049,
  4628,
  6154,
  5720,
  6023,
  6536,
  6667,
  7111,
  6414,
  5907,
  7246,
  7254,
  8138,
  8364,
  8789,
  7723,
  8812,
  9689,
  9847,
  9472,
  10408,
  10882,
  8536,
  9981,
  11156,
  11135,
  11306,
  12039,
  11405,
  10032,
  11086,
  13108,
  13829,
  14740,
  15918,
  15151,
  13560,
  15656,
  16868,
  18205,
  18255,
  20142,
  19610,
  18339,
  18256,
  19429,
  21947,
  22718,
  24018,
  23942,
  22500,
  23147,
  25561,
  25790,
  27762,
  27757,
  29106,
  28178,
  29917,
  32607,
  35468,
  34820,
  37411,
  40235,
  36806,
  39170,
  45601,
  48443,
  48888,
  50072,
  48932,
  46484,
  49631,
  52479,
  54968,
  57486,
  55117,
  52672,
  50488,
  51282,
  56626,
  62170,
  61455,
  65156,
  62117,
  53016,
  61252,
  67066,
  64141,
  65610,
  63986,
  58096,
  54298,
  65024,
  69196,
  68518,
  69029,
  70067,
  61749,
  59696,
  66873,
  75995,
  76827,
  76657,
  78479,
  79461,
  68766,
  78168,
  82860,
  84156,
  87115,
  90600,
  91725,
  75015,
  89855,
  95536,
  96762,
  97655,
  94414,
  93220,
  81913,
  91098,
  97860,
  96787,
  92973,
  92574,
  87395,
  74493,
  83362,
  86703,
  85921,
  85717,
  88759,
  82770,
  69669,
  80500,
  86748,
  81784,
  79883,
  75479,
  74770,
  60130,
  71869,
  78809,
  70797,
  73305,
  74418,
  67789,
  54261,
  63520,
  67811,
  63441,
  62302,
  61893,
  55035,
  45506,
  54348,
  56264,
  53931,
  50366,
  45922,
  36019,
  43034,
  0],
 'pprd_val': [291,
  401,
  420,
  557,
  525,
  599,
  474,
  567,
  'No',
  721,
  860,
  693,
  731,
  1170,
  949,
  855,
  1015,
  'No',
  1290,
  1545,
  'No',
  1271,
  'No',
  1397,
  972,
  1819,
  1607,
  1551,
  1651,
  1690,
  1766,
  2202,
  2435,
  2744,
  3399,
  2756,
  3430,
  3204,
  3104,
  2414,
  4076,
  3104,
  3523,
  3701,
  3898,
  3802,
  4437,
  4997,
  4291,
  5316,
  5006,
  5318,
  6449,
  6055,
  7036,
  6342,
  5785,
  7088,
  6815,
  7485,
  7811,
  8683,
  7712,
  7974,
  9376,
  9579,
  9187,
  10220,
  10775,
  'No',
  9867,
  11155,
  10319,
  11114,
  11676,
  11018,
  'No',
  10308,
  12820,
  13532,
  14590,
  15711,
  13903,
  12763,
  14579,
  16817,
  18174,
  18159,
  18883,
  19436,
  18185,
  17150,
  18967,
  20844,
  22587,
  23516,
  23289,
  21884,
  22511,
  25448,
  24380,
  26452,
  27248,
  28376,
  27207,
  29885,
  31763,
  33788,
  32821,
  36672,
  40195,
  36664,
  38500,
  43853,
  47963,
  46981,
  49337,
  46158,
  44382,
  49337,
  51895,
  53589,
  56013,
  54918,
  50007,
  50354,
  51146,
  56569,
  59728,
  60864,
  62874,
  60561,
  'No',
  60748,
  63116,
  63545,
  64711,
  63487,
  'No',
  52748,
  62484,
  67924,
  66943,
  67847,
  69959,
  'No',
  57646,
  63982,
  74913,
  76615,
  69959,
  78237,
  72582,
  'No',
  76506,
  81545,
  84129,
  85501,
  90178,
  87834,
  'No',
  85652,
  94224,
  93260,
  91808,
  93015,
  92615,
  'No',
  83270,
  93345,
  93825,
  92255,
  92559,
  'No',
  'No',
  77101,
  82589,
  85476,
  85426,
  85513,
  'No',
  'No',
  70091,
  82790,
  77185,
  77570,
  'No',
  74096,
  'No',
  61957,
  75073,
  'No',
  72129,
  72941,
  'No',
  'No',
  56173,
  62862,
  61750,
  62113,
  61258,
  'No',
  'No',
  48446,
  53478,
  51612,
  'No',
  'No',
  'No',
  39354,
  'No'],
 'nprd_val': [321,
  511,
  563,
  666,
  645,
  629,
  557,
  578,
  586,
  'No',
  888,
  924,
  837,
  1253,
  1330,
  981,
  1369,
  1021,
  1582,
  1704,
  1271,
  1620,
  1332,
  1709,
  1503,
  1907,
  1955,
  1648,
  1932,
  1955,
  1802,
  2479,
  2619,
  3411,
  3927,
  3003,
  3946,
  3399,
  3395,
  3199,
  4367,
  3734,
  3640,
  4479,
  4377,
  3932,
  5075,
  5145,
  5130,
  6356,
  6035,
  6139,
  6589,
  7093,
  7746,
  6470,
  6727,
  7717,
  7530,
  8260,
  8439,
  8838,
  7823,
  9075,
  9871,
  10133,
  10002,
  11235,
  11436,
  9877,
  11026,
  11436,
  11222,
  11415,
  12261,
  11414,
  10226,
  11310,
  13456,
  15499,
  16351,
  17428,
  15222,
  14022,
  15711,
  17190,
  19475,
  18995,
  21077,
  20902,
  19092,
  18305,
  20440,
  22224,
  24791,
  25662,
  24671,
  23866,
  23202,
  27131,
  25846,
  28480,
  28604,
  30657,
  28652,
  30083,
  33037,
  35539,
  37152,
  38657,
  40775,
  37156,
  41878,
  'No',
  53088,
  50776,
  51434,
  51285,
  46818,
  51870,
  52991,
  55490,
  57575,
  58880,
  52846,
  53294,
  53958,
  57809,
  62527,
  63383,
  68649,
  62527,
  55743,
  64962,
  67139,
  67608,
  67662,
  64057,
  60910,
  56185,
  67113,
  74970,
  69777,
  69425,
  76668,
  65865,
  62546,
  67340,
  78491,
  77269,
  77668,
  79202,
  80017,
  74346,
  81357,
  86773,
  87834,
  89078,
  90776,
  92742,
  84376,
  90178,
  102898,
  98021,
  98004,
  98556,
  95495,
  90619,
  94302,
  98078,
  98437,
  93511,
  97425,
  91950,
  82506,
  89309,
  88520,
  86513,
  91683,
  91779,
  84376,
  77185,
  82766,
  88681,
  83241,
  81588,
  78026,
  75162,
  74020,
  75857,
  85900,
  74068,
  78817,
  74722,
  72380,
  61750,
  69698,
  68271,
  66468,
  62861,
  63656,
  60663,
  48937,
  59034,
  57890,
  55130,
  53157,
  47037,
  41870,
  48869,
  41917]}

In [36]:
err_df=pd.DataFrame(err_dict)
err_df

            date  mipe  mxne  mipv    mxnv  original_val pprd_val nprd_val
0    2020-03-31     lb   mdb    18     -12           309      291      321
1    2020-04-01   memb    lb    23     -87           424      401      511
2    2020-04-02   mxmb  memb    66     -77           486      420      563
3    2020-04-03     lb  memb     3    -106           560      557      666
4    2020-04-04   mxmb    lb    54     -66           579      525      645
..           ...   ...   ...   ...     ...           ...      ...      ...
206  2020-10-24     No   mlb    No   -2791         50366       No    53157
207  2020-10-25     No    lb    No   -1115         45922       No    47037
208  2020-10-26     No    lb    No   -5851         36019       No    41870
209  2020-10-27    lmb    mb  3680   -5835         43034    39354    48869
210  2020-10-28     No   mlb    No  -41917             0       No    41917

[211 rows x 8 columns]

In [37]:
err_df.to_excel("dcerr_df.xlsx")
errdf=pd.read_excel(r"C:\Users\Mark 1\dcerr_df.xlsx")
errdf = errdf.loc[:, ~errdf.columns.str.contains('^Unnamed')]
errdf.to_excel("dcerr_df.xlsx")

In [38]:
Counter(err_df['mipe'])

Counter({'lb': 23,
         'memb': 28,
         'mxmb': 26,
         'lmb': 29,
         'mlb': 20,
         'No': 27,
         'mxb': 2,
         'mb': 41,
         'mdb': 15})

In [39]:
mnval=max(list(Counter(err_df['mipe']).values()))
mnvalidx=list(Counter(err_df['mipe']).values()).index(mnval)
mnkys=list(Counter(err_df['mipe']).keys())[mnvalidx]
print("method: "+mnkys+" and values is: ",Counter(err_df['mipe'])[mnkys])

method: mb and values is:  41

In [40]:
Counter(err_df['mxne'])

Counter({'mdb': 16,
         'lb': 25,
         'memb': 46,
         'mxmb': 26,
         'mb': 31,
         'No': 2,
         'mxb': 26,
         'mlb': 17,
         'lmb': 22})

In [41]:
mxval=max(list(Counter(err_df['mxne']).values()))
mxvalidx=list(Counter(err_df['mxne']).values()).index(mxval)
mxkys=list(Counter(err_df['mxne']).keys())[mxvalidx]
print("method: "+mxkys+" and values is: ",Counter(err_df['mxne'])[mxkys])

method: memb and values is:  46

In [42]:
err_df['mipe'][len(err_df)-2]

'lmb'

In [43]:
err_df['mxne'][len(err_df)-2]

'mb'