In [1]:
import pandas as pd
import numpy as np 
import copy
from matplotlib import pyplot as plt
import seaborn as sns
from collections import *
import datetime

In [2]:
data=pd.read_csv(r"C:\Users\Mark 1\Desktop\Lockdown\data\Covid-19\117\case_time_series.csv")
data.head()

,Date,Daily Confirmed,Total Confirmed,Daily Recovered,Total Recovered,Daily Deceased,Total Deceased
0,30-Jan,1,1,0,0,0,0
1,31-Jan,0,1,0,0,0,0
2,01-Feb,0,1,0,0,0,0
3,02-Feb,1,2,0,0,0,0
4,03-Feb,1,3,0,0,0,0

In [3]:
data_total=data[53:]
data_total.reset_index(drop=True,inplace=True)
data_total.head()

,Date,Daily Confirmed,Total Confirmed,Daily Recovered,Total Recovered,Daily Deceased,Total Deceased
0,23-Mar,94,497,2,25,2,9
1,24-Mar,74,571,15,40,1,10
2,25-Mar,86,657,3,43,1,11
3,26-Mar,73,730,7,50,5,16
4,27-Mar,153,883,25,75,3,19

In [4]:
data_total.tail()

,Date,Daily Confirmed,Total Confirmed,Daily Recovered,Total Recovered,Daily Deceased,Total Deceased
214,23-Oct,53931,7813676,66994,7013541,655,117406
215,24-Oct,50366,7864042,62270,7075811,578,117984
216,25-Oct,45922,7909964,59304,7135115,483,118467
217,26-Oct,36019,7945983,63734,7198849,485,118952
218,27-Oct,43034,7989017,58428,7257277,517,119469

In [5]:
colls=list(data_total.columns)
colls

['Date',
 'Daily Confirmed',
 'Total Confirmed',
 'Daily Recovered',
 'Total Recovered',
 'Daily Deceased',
 'Total Deceased']

In [6]:
data_total.dtypes

Date               object
Daily Confirmed     int64
Total Confirmed     int64
Daily Recovered     int64
Total Recovered     int64
Daily Deceased      int64
Total Deceased      int64
dtype: object

In [7]:
data_total[data_total.duplicated()]

Empty DataFrame
Columns: [Date, Daily Confirmed, Total Confirmed, Daily Recovered, Total Recovered, Daily Deceased, Total Deceased]
Index: []

In [8]:
data_total['Date'] = data_total['Date'].astype('str')

<ipython-input-8-99f82638761e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_total['Date'] = data_total['Date'].astype('str')

In [9]:
for i in range(0,9):
    data_total["Date"][i]=data_total["Date"][i].strip(" March")
for i in range(0,9):
    data_total["Date"][i]="2020-03-"+data_total["Date"][i]

<ipython-input-9-d239740191b3>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_total["Date"][i]=data_total["Date"][i].strip(" March")
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3343: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
<ipython-input-9-d239740191b3>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_total["Date"][i]="2020-03-"+data_total["Date"][i]

In [10]:
for i in range(9,39):
    data_total["Date"][i]=data_total["Date"][i].strip(" April")
for i in range(9,39):
    data_total["Date"][i]="2020-04-"+data_total["Date"][i]

<ipython-input-10-aa71c839161c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_total["Date"][i]=data_total["Date"][i].strip(" April")
<ipython-input-10-aa71c839161c>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_total["Date"][i]="2020-04-"+data_total["Date"][i]

In [11]:
for i in range(39,70):
    data_total["Date"][i]=data_total["Date"][i].strip(" May")
for i in range(39,70):
    data_total["Date"][i]="2020-05-"+data_total["Date"][i]

<ipython-input-11-53c499d84780>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_total["Date"][i]=data_total["Date"][i].strip(" May")
<ipython-input-11-53c499d84780>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_total["Date"][i]="2020-05-"+data_total["Date"][i]

In [12]:
for i in range(70,100):
    data_total["Date"][i]=data_total["Date"][i].strip(" June")
for i in range(70,100):
    data_total["Date"][i]="2020-06-"+data_total["Date"][i]

<ipython-input-12-1a0a85fafe5b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_total["Date"][i]=data_total["Date"][i].strip(" June")
<ipython-input-12-1a0a85fafe5b>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_total["Date"][i]="2020-06-"+data_total["Date"][i]

In [13]:
for i in range(100,131):
    data_total["Date"][i]=data_total["Date"][i].strip(" July")
for i in range(100,131):
    data_total["Date"][i]="2020-07-"+data_total["Date"][i]

<ipython-input-13-208466873f51>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_total["Date"][i]=data_total["Date"][i].strip(" July")
<ipython-input-13-208466873f51>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_total["Date"][i]="2020-07-"+data_total["Date"][i]

In [14]:

for i in range(131,162):
    data_total["Date"][i]=data_total["Date"][i].strip(" August")
for i in range(131,162):
    data_total["Date"][i]="2020-08-"+data_total["Date"][i]

<ipython-input-14-16f669050c92>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_total["Date"][i]=data_total["Date"][i].strip(" August")
<ipython-input-14-16f669050c92>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_total["Date"][i]="2020-08-"+data_total["Date"][i]

In [15]:

for i in range(162,192):
    data_total["Date"][i]=data_total["Date"][i].strip(" September")
for i in range(162,192):
    data_total["Date"][i]="2020-09-"+data_total["Date"][i]

<ipython-input-15-2668c5c83263>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_total["Date"][i]=data_total["Date"][i].strip(" September")
<ipython-input-15-2668c5c83263>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_total["Date"][i]="2020-09-"+data_total["Date"][i]

In [16]:

for i in range(192,len(data_total)):
    data_total["Date"][i]=data_total["Date"][i].strip(" October")
for i in range(192,len(data_total)):
    data_total["Date"][i]="2020-10-"+data_total["Date"][i]

<ipython-input-16-e530b2cfaa41>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_total["Date"][i]=data_total["Date"][i].strip(" October")
<ipython-input-16-e530b2cfaa41>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_total["Date"][i]="2020-10-"+data_total["Date"][i]

In [17]:
data_total["Date"]=data_total["Date"].astype('datetime64[ns]')

<ipython-input-17-a317546e137f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_total["Date"]=data_total["Date"].astype('datetime64[ns]')

In [18]:
data_total.dtypes

The history saving thread hit an unexpected error (OperationalError('database is locked')).History will not be written to the database.

Date               datetime64[ns]
Daily Confirmed             int64
Total Confirmed             int64
Daily Recovered             int64
Total Recovered             int64
Daily Deceased              int64
Total Deceased              int64
dtype: object

In [19]:
data_total_ratio_with_two_precision=data_total.copy()

In [20]:
new_cols=["Daily_Confirmed_Ratio","Total_Confirmed_Ratio","Daily_Recovered_Ratio","Total_Recovered_Ratio","Daily_Deceased_Ratio","Total_Deceased_Ratio"]
existing_cols=list(data_total_ratio_with_two_precision.columns)
existing_cols.pop(0)
existing_cols
for i,j in zip(new_cols,existing_cols):
    data_total_ratio_with_two_precision[i]=list(range(len(data_total_ratio_with_two_precision)))
    data_total_ratio_with_two_precision[i][0]=1
    tmp=[]
    tmp.append(data_total_ratio_with_two_precision[i][0])
    for k in range(0,len(data_total_ratio_with_two_precision)-1):
        tmp.append(round(data_total_ratio_with_two_precision[j][k+1]/data_total_ratio_with_two_precision[j][k],2))
    data_total_ratio_with_two_precision[i]=tmp
data_total_ratio_with_two_precision.head()

<ipython-input-20-c038b6b9f526>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_total_ratio_with_two_precision[i][0]=1

,Date,Daily Confirmed,Total Confirmed,Daily Recovered,Total Recovered,Daily Deceased,Total Deceased,Daily_Confirmed_Ratio,Total_Confirmed_Ratio,Daily_Recovered_Ratio,Total_Recovered_Ratio,Daily_Deceased_Ratio,Total_Deceased_Ratio
0,2020-03-23,94,497,2,25,2,9,1.00,1.00,1.00,1.00,1.0,1.00
1,2020-03-24,74,571,15,40,1,10,0.79,1.15,7.50,1.60,0.5,1.11
2,2020-03-25,86,657,3,43,1,11,1.16,1.15,0.20,1.08,1.0,1.10
3,2020-03-26,73,730,7,50,5,16,0.85,1.11,2.33,1.16,5.0,1.45
4,2020-03-27,153,883,25,75,3,19,2.10,1.21,3.57,1.50,0.6,1.19

In [21]:
data_total_ratio=data_total.copy()

In [22]:
new_cols=["Daily_Confirmed_Ratio","Total_Confirmed_Ratio","Daily_Recovered_Ratio","Total_Recovered_Ratio","Daily_Deceased_Ratio","Total_Deceased_Ratio"]
existing_cols=list(data_total_ratio.columns)
existing_cols.pop(0)
existing_cols
for i,j in zip(new_cols,existing_cols):
    data_total_ratio[i]=list(range(len(data_total_ratio)))
    data_total_ratio[i][0]=1
    tmp=[]
    tmp.append(data_total_ratio[i][0])
    for k in range(0,len(data_total_ratio)-1):
        tmp.append(data_total_ratio[j][k+1]/data_total_ratio[j][k])
    data_total_ratio[i]=tmp
data_total_ratio.head()

<ipython-input-22-6e1737506d3a>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_total_ratio[i][0]=1

,Date,Daily Confirmed,Total Confirmed,Daily Recovered,Total Recovered,Daily Deceased,Total Deceased,Daily_Confirmed_Ratio,Total_Confirmed_Ratio,Daily_Recovered_Ratio,Total_Recovered_Ratio,Daily_Deceased_Ratio,Total_Deceased_Ratio
0,2020-03-23,94,497,2,25,2,9,1.000000,1.000000,1.000000,1.000000,1.0,1.000000
1,2020-03-24,74,571,15,40,1,10,0.787234,1.148893,7.500000,1.600000,0.5,1.111111
2,2020-03-25,86,657,3,43,1,11,1.162162,1.150613,0.200000,1.075000,1.0,1.100000
3,2020-03-26,73,730,7,50,5,16,0.848837,1.111111,2.333333,1.162791,5.0,1.454545
4,2020-03-27,153,883,25,75,3,19,2.095890,1.209589,3.571429,1.500000,0.6,1.187500

In [23]:
strt_cnt=1
end_cnt=8
strt_lst=[]
end_lst=[]
strt_lst.append(strt_cnt)
end_lst.append(end_cnt)
while(end_cnt<=len(data_total_ratio)):
        strt_cnt+=1
        strt_lst.append(strt_cnt)
        end_cnt+=1
        end_lst.append(end_cnt)
if(end_lst[len(end_lst)-1]>=len(data_total_ratio)):
    end_lst.pop(len(end_lst)-1)
strt_lst.pop(len(strt_lst)-1)
#print(strt_lst)
#print(end_lst)
#print(len(strt_lst)==len(end_lst))

for st,en in zip(strt_lst,end_lst):

    dcr=data_total_ratio.iloc[st:en,10:11]
    dcr.reset_index(inplace = True, drop = True)
    dc=data_total_ratio.iloc[st:en,4:5]
    dc.reset_index(inplace = True, drop = True)



    next_day_recovered_case_count_mean_based=dcr.mean()[0]*dc.mean()[0]

    next_day_recovered_case_count_max_based=max(dcr["Total_Recovered_Ratio"])*max(dc["Total Recovered"])


    next_day_recovered_case_count_mean_max_based=dcr.mean()[0]*max(dc["Total Recovered"])


    next_day_recovered_case_count_max_mean_based=max(dcr["Total_Recovered_Ratio"])*dc.mean()[0]


    next_day_recovered_case_count_mean_last_based=dcr.mean()[0]*dc["Total Recovered"][len(dc)-1]


    next_day_recovered_case_count_last_mean_based=dcr["Total_Recovered_Ratio"][len(dcr)-1]*dc.mean()[0]


    next_day_recovered_case_count_last_based=dcr["Total_Recovered_Ratio"][len(dcr)-1]*dc["Total Recovered"][len(dc)-1]


    next_day_recovered_case_count_middle_based=dcr["Total_Recovered_Ratio"][3]*dc["Total Recovered"][3]


    pred_val=[]
    pred_val.append(np.round(next_day_recovered_case_count_mean_based))
    pred_val.append(np.round(next_day_recovered_case_count_max_based))
    pred_val.append(np.round(next_day_recovered_case_count_mean_max_based))
    pred_val.append(np.round(next_day_recovered_case_count_max_mean_based))
    pred_val.append(np.round(next_day_recovered_case_count_mean_last_based))
    pred_val.append(np.round(next_day_recovered_case_count_last_mean_based))
    pred_val.append(np.round(next_day_recovered_case_count_last_based))
    pred_val.append(np.round(next_day_recovered_case_count_middle_based))


    
    if(en<len(data_total_ratio)):
        pred_dict={"date":data_total_ratio["Date"][en-1]+datetime.timedelta(hours=24),"original_val":data_total_ratio["Total Recovered"][en],"mean_based":pred_val[0],"max_based":pred_val[1],"mean_max_based":pred_val[2],"max_mean_based":pred_val[3],"mean_last_based":pred_val[4],"last_mean_based":pred_val[5],"last_based":pred_val[6],"middle_based":pred_val[7]}
    else:
        pred_dict={"date":data_total_ratio["Date"][en-1]+datetime.timedelta(hours=24),"original_val":0,"mean_based":pred_val[0],"max_based":pred_val[1],"mean_max_based":pred_val[2],"max_mean_based":pred_val[3],"mean_last_based":pred_val[4],"last_mean_based":pred_val[5],"last_based":pred_val[6],"middle_based":pred_val[7]}
        
        
        
    
    
    pred_df=pd.DataFrame(pred_dict, index=[0])
    
    

d=pd.read_excel(r"C:\Users\Mark 1\tramprd_df_strd.xlsx")
d=pd.concat([d,pred_df])
d.reset_index(drop=True,inplace=True)
d['original_val'][len(d)-2]=data_total_ratio['Total Recovered'][len(data_total_ratio)-1]
d.to_excel("tramprd_df_strd.xlsx")

<ipython-input-23-f50cc3349488>:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d['original_val'][len(d)-2]=data_total_ratio['Total Recovered'][len(data_total_ratio)-1]

In [24]:
tc=pd.read_excel(r"C:\Users\Mark 1\tramprd_df_strd.xlsx")
tc = tc.loc[:, ~tc.columns.str.contains('^Unnamed')]
tc.tail()

,date,original_val,mean_based,max_based,mean_max_based,max_mean_based,mean_last_based,last_mean_based,last_based,middle_based
207,2020-10-24,7075811,6872464,7095692,7086758,6881129,7086758,6867056,7081181,6854813
208,2020-10-25,7135115,6939750,7158691,7147402,6950711,7147402,6931237,7138634,6952471
209,2020-10-26,7198849,7006521,7218690,7205583,7019266,7205583,6996149,7194916,7021925
210,2020-10-27,7257277,7072528,7283171,7268356,7086944,7268356,7067465,7263152,7081181
211,2020-10-28,0,7138497,7342283,7326239,7154130,7326239,7128695,7316179,7138634

In [25]:
tce=tc.copy()

In [26]:
colls=list(tc.columns)
colls.pop(0)
colls.pop(0)
collss=["mb","mxb","memb","mxmb","mlb","lmb","lb","mdb"]
for i in collss:
    tce[i]=pd.Series(range(1,len(tce)+1))
colls

['mean_based',
 'max_based',
 'mean_max_based',
 'max_mean_based',
 'mean_last_based',
 'last_mean_based',
 'last_based',
 'middle_based']

In [27]:
for i,j in zip(colls,collss):
    for k in range(len(tce)):
        tce[j][k]=tce["original_val"][k]-tce[i][k]
tce

<ipython-input-27-35e3607d3c2a>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tce[j][k]=tce["original_val"][k]-tce[i][k]

,date,original_val,mean_based,max_based,mean_max_based,max_mean_based,mean_last_based,last_mean_based,last_based,middle_based,mb,mxb,memb,mxmb,mlb,lmb,lb,mdb
0,2020-03-31,150,98,219,176,122,176,102,184,112,52,-69,-26,28,-26,48,-34,38
1,2020-04-01,169,111,225,182,138,182,100,164,96,58,-56,-13,31,-13,69,5,73
2,2020-04-02,191,134,254,207,165,207,124,190,122,57,-63,-16,26,-16,67,1,69
3,2020-04-03,230,158,286,233,195,233,147,216,184,72,-56,-3,35,-3,83,14,46
4,2020-04-04,286,179,309,270,204,270,183,277,164,107,-23,16,82,16,103,9,122
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,2020-10-24,7075811,6872464,7095692,7086758,6881129,7086758,6867056,7081181,6854813,203347,-19881,-10947,194682,-10947,208755,-5370,220998
208,2020-10-25,7135115,6939750,7158691,7147402,6950711,7147402,6931237,7138634,6952471,195365,-23576,-12287,184404,-12287,203878,-3519,182644
209,2020-10-26,7198849,7006521,7218690,7205583,7019266,7205583,6996149,7194916,7021925,192328,-19841,-6734,179583,-6734,202700,3933,176924
210,2020-10-27,7257277,7072528,7283171,7268356,7086944,7268356,7067465,7263152,7081181,184749,-25894,-11079,170333,-11079,189812,-5875,176096
211,2020-10-28,0,7138497,7342283,7326239,7154130,7326239,7128695,7316179,7138634,-7138497,-7342283,-7326239,-7154130,-7326239,-7128695,-7316179,-7138634

In [28]:
tce.to_excel("tramerrprd_df_strd.xlsx")
tce=pd.read_excel(r"C:\Users\Mark 1\tramerrprd_df_strd.xlsx")
tce = tce.loc[:, ~tce.columns.str.contains('^Unnamed')]
tce.to_excel("tramerrprd_df_strd.xlsx")

In [29]:
edf=tce.iloc[0:len(tce),10:]
edf

          mb      mxb     memb     mxmb      mlb      lmb       lb      mdb
0         52      -69      -26       28      -26       48      -34       38
1         58      -56      -13       31      -13       69        5       73
2         57      -63      -16       26      -16       67        1       69
3         72      -56       -3       35       -3       83       14       46
4        107      -23       16       82       16      103        9      122
..       ...      ...      ...      ...      ...      ...      ...      ...
207   203347   -19881   -10947   194682   -10947   208755    -5370   220998
208   195365   -23576   -12287   184404   -12287   203878    -3519   182644
209   192328   -19841    -6734   179583    -6734   202700     3933   176924
210   184749   -25894   -11079   170333   -11079   189812    -5875   176096
211 -7138497 -7342283 -7326239 -7154130 -7326239 -7128695 -7316179 -7138634

[212 rows x 8 columns]

In [30]:

for j,k in zip(range(len(edf)),range(len(tce)-1)):
    
    a=list(edf.loc[j])
    pos=[]
    neg=[]
    for i in a:
        if(i>=0):
            pos.append(i)
        else:
            neg.append(i)
    if(len(pos)):
        ps=min(pos)
        psi=a.index(ps)
        psc=list(edf.columns)[psi]
    if(len(neg)):
        ng=max(neg)
        ngi=a.index(ng)
        ngc=list(edf.columns)[ngi]
    
    
    print("for date: "+str(tce["date"][k]).strip("00:00:00")+" the lowest positve error was by the method: "+psc+" and the highest negative error by the method: "+ngc)

for date: 2020-03-31  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-04-01  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-04-02  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-04-03  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-04-04  the lowest positve error was by the method: lb and the highest negative error by the method: mxb
for date: 2020-04-05  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-04-06  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-04-07  the lowest positve error was by the method: memb and the highest negative error by the method: lb
for date: 2020-04-08  the lowest positve error was by the method: lb and the highest negative error by the method: mxb
for date: 2020-04-09  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-04-10  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-04-11  the lowest positve error was by the method: memb and the highest negative error by the method: lb
for date: 2020-04-12  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-04-13  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-04-14  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-04-15  the lowest positve error was by the method: mdb and the highest negative error by the method: lb
for date: 2020-04-16  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-04-17  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-04-18  the lowest positve error was by the method: lb and the highest negative error by the method: mxb
for date: 2020-04-19  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-04-20  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-04-21  the lowest positve error was by the method: mxb and the highest negative error by the method: memb
for date: 2020-04-22  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-04-23  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-04-24  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-04-25  the lowest positve error was by the method: mdb and the highest negative error by the method: lb
for date: 2020-04-26  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-04-27  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-04-28  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-04-29  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-04-30  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-05-01  the lowest positve error was by the method: mxb and the highest negative error by the method: lb
for date: 2020-05-02  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-05-03  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-05-04  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-05-05  the lowest positve error was by the method: lb and the highest negative error by the method: mxb
for date: 2020-05-06  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-05-07  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-05-08  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-05-09  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-05-10  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-05-11  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-05-12  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-05-13  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-05-14  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-05-15  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-05-16  the lowest positve error was by the method: mxb and the highest negative error by the method: mxb
for date: 2020-05-17  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-05-18  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-05-19  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-05-20  the lowest positve error was by the method: mdb and the highest negative error by the method: lb
for date: 2020-05-21  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-05-22  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-05-23  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-05-24  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-05-25  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-05-26  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-05-27  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-05-28  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-05-29  the lowest positve error was by the method: mxb and the highest negative error by the method: lb
for date: 2020-05-30  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-05-31  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-06-01  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-06-02  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-06-03  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-06-04  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-06-05  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-06-06  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-06-07  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-06-08  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-06-09  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-06-10  the lowest positve error was by the method: lb and the highest negative error by the method: mxb
for date: 2020-06-11  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-06-12  the lowest positve error was by the method: mxb and the highest negative error by the method: memb
for date: 2020-06-13  the lowest positve error was by the method: mxb and the highest negative error by the method: memb
for date: 2020-06-14  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-06-15  the lowest positve error was by the method: mxb and the highest negative error by the method: memb
for date: 2020-06-16  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-06-17  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-06-18  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-06-19  the lowest positve error was by the method: mdb and the highest negative error by the method: memb
for date: 2020-06-20  the lowest positve error was by the method: mxb and the highest negative error by the method: memb
for date: 2020-06-21  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-06-22  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-06-23  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-06-24  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-06-25  the lowest positve error was by the method: lb and the highest negative error by the method: mxb
for date: 2020-06-26  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-06-27  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-06-28  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-06-29  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-06-30  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-07-01  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-07-02  the lowest positve error was by the method: mxb and the highest negative error by the method: lb
for date: 2020-07-03  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-07-04  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-07-05  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-07-06  the lowest positve error was by the method: mdb and the highest negative error by the method: lb
for date: 2020-07-07  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-07-08  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-07-09  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-07-10  the lowest positve error was by the method: lb and the highest negative error by the method: mxb
for date: 2020-07-11  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-07-12  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-07-13  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-07-14  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-07-15  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-07-16  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-07-17  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-07-18  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-07-19  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-07-20  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-07-21  the lowest positve error was by the method: mxb and the highest negative error by the method: mxb
for date: 2020-07-22  the lowest positve error was by the method: mxb and the highest negative error by the method: mxb
for date: 2020-07-23  the lowest positve error was by the method: mxb and the highest negative error by the method: mxb
for date: 2020-07-24  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-07-25  the lowest positve error was by the method: mxb and the highest negative error by the method: mxb
for date: 2020-07-26  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-07-27  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-07-28  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-07-29  the lowest positve error was by the method: mdb and the highest negative error by the method: lb
for date: 2020-07-30  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-07-31  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-08-01  the lowest positve error was by the method: mxb and the highest negative error by the method: lb
for date: 2020-08-02  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-08-03  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-08-04  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-08-05  the lowest positve error was by the method: mdb and the highest negative error by the method: memb
for date: 2020-08-06  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-08-07  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-08-08  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-08-09  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-08-10  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-08-11  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-08-12  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-08-13  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-08-14  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-08-15  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-08-16  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-08-17  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-08-18  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-08-19  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-08-20  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-08-21  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-08-22  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-08-23  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-08-24  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-08-25  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-08-26  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-08-27  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-08-28  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-08-29  the lowest positve error was by the method: mdb and the highest negative error by the method: lb
for date: 2020-08-30  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-08-31  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-09-01  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-09-02  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-09-03  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-09-04  the lowest positve error was by the method: lb and the highest negative error by the method: memb
for date: 2020-09-05  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-09-06  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-09-07  the lowest positve error was by the method: memb and the highest negative error by the method: mxb
for date: 2020-09-08  the lowest positve error was by the method: mxmb and the highest negative error by the method: memb
for date: 2020-09-09  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-09-10  the lowest positve error was by the method: mxmb and the highest negative error by the method: lb
for date: 2020-09-11  the lowest positve error was by the method: memb and the highest negative error by the method: mxb

In [31]:
err_dict={"date":[],"mipe":[],"mxne":[],"mipv":[],"mxnv":[],"original_val":[],"pprd_val":[],"nprd_val":[]}
psc=[]
ngc=[]
date=[]
ps=[]
ng=[]
org_val=[]
pprd_val=[]
nprd_val=[]
for j,k in zip(range(len(edf)),range(len(tce))):
    
    a=list(edf.loc[j])
    pos=[]
    neg=[]
    for i in a:
        if(i>=0):
            pos.append(i)
        else:
            neg.append(i)
    if(len(pos)):
        aa=min(pos)
    
        psi=a.index(aa)
    
        ps.append(aa)
    
        psc.append(list(edf.columns)[psi])
    
    
        pprd_val.append(tce["original_val"][k]-aa)
    else:
        ps.append("No")
    
        psc.append("No")
    
    
        pprd_val.append("No")
        
    
    if(len(neg)):
        bb=max(neg)
        ngi=a.index(bb)
        ng.append(bb)
        ngc.append(list(edf.columns)[ngi])
        nprd_val.append(tce["original_val"][k]-bb)
    else:
        ng.append("No")
    
        ngc.append("No")
    
    
        nprd_val.append("No")
    
    date.append(str(tce["date"][k]).strip("00:00:00"))
    org_val.append(tce["original_val"][k])
err_dict.update({"date":date})
err_dict.update({"mipe":psc})
err_dict.update({"mxne":ngc})
err_dict.update({"mipv":ps})
err_dict.update({"mxnv":ng})
err_dict.update({"original_val":org_val})
err_dict.update({"pprd_val":pprd_val})
err_dict.update({"nprd_val":nprd_val})

In [32]:
err_dict

{'date': ['2020-03-31 ',
  '2020-04-01 ',
  '2020-04-02 ',
  '2020-04-03 ',
  '2020-04-04 ',
  '2020-04-05 ',
  '2020-04-06 ',
  '2020-04-07 ',
  '2020-04-08 ',
  '2020-04-09 ',
  '2020-04-10 ',
  '2020-04-11 ',
  '2020-04-12 ',
  '2020-04-13 ',
  '2020-04-14 ',
  '2020-04-15 ',
  '2020-04-16 ',
  '2020-04-17 ',
  '2020-04-18 ',
  '2020-04-19 ',
  '2020-04-20 ',
  '2020-04-21 ',
  '2020-04-22 ',
  '2020-04-23 ',
  '2020-04-24 ',
  '2020-04-25 ',
  '2020-04-26 ',
  '2020-04-27 ',
  '2020-04-28 ',
  '2020-04-29 ',
  '2020-04-30 ',
  '2020-05-01 ',
  '2020-05-02 ',
  '2020-05-03 ',
  '2020-05-04 ',
  '2020-05-05 ',
  '2020-05-06 ',
  '2020-05-07 ',
  '2020-05-08 ',
  '2020-05-09 ',
  '2020-05-10 ',
  '2020-05-11 ',
  '2020-05-12 ',
  '2020-05-13 ',
  '2020-05-14 ',
  '2020-05-15 ',
  '2020-05-16 ',
  '2020-05-17 ',
  '2020-05-18 ',
  '2020-05-19 ',
  '2020-05-20 ',
  '2020-05-21 ',
  '2020-05-22 ',
  '2020-05-23 ',
  '2020-05-24 ',
  '2020-05-25 ',
  '2020-05-26 ',
  '2020-05-27 ',
  '2020-05-28 ',
  '2020-05-29 ',
  '2020-05-30 ',
  '2020-05-31 ',
  '2020-06-01 ',
  '2020-06-02 ',
  '2020-06-03 ',
  '2020-06-04 ',
  '2020-06-05 ',
  '2020-06-06 ',
  '2020-06-07 ',
  '2020-06-08 ',
  '2020-06-09 ',
  '2020-06-10 ',
  '2020-06-11 ',
  '2020-06-12 ',
  '2020-06-13 ',
  '2020-06-14 ',
  '2020-06-15 ',
  '2020-06-16 ',
  '2020-06-17 ',
  '2020-06-18 ',
  '2020-06-19 ',
  '2020-06-20 ',
  '2020-06-21 ',
  '2020-06-22 ',
  '2020-06-23 ',
  '2020-06-24 ',
  '2020-06-25 ',
  '2020-06-26 ',
  '2020-06-27 ',
  '2020-06-28 ',
  '2020-06-29 ',
  '2020-06-30 ',
  '2020-07-01 ',
  '2020-07-02 ',
  '2020-07-03 ',
  '2020-07-04 ',
  '2020-07-05 ',
  '2020-07-06 ',
  '2020-07-07 ',
  '2020-07-08 ',
  '2020-07-09 ',
  '2020-07-10 ',
  '2020-07-11 ',
  '2020-07-12 ',
  '2020-07-13 ',
  '2020-07-14 ',
  '2020-07-15 ',
  '2020-07-16 ',
  '2020-07-17 ',
  '2020-07-18 ',
  '2020-07-19 ',
  '2020-07-20 ',
  '2020-07-21 ',
  '2020-07-22 ',
  '2020-07-23 ',
  '2020-07-24 ',
  '2020-07-25 ',
  '2020-07-26 ',
  '2020-07-27 ',
  '2020-07-28 ',
  '2020-07-29 ',
  '2020-07-30 ',
  '2020-07-31 ',
  '2020-08-01 ',
  '2020-08-02 ',
  '2020-08-03 ',
  '2020-08-04 ',
  '2020-08-05 ',
  '2020-08-06 ',
  '2020-08-07 ',
  '2020-08-08 ',
  '2020-08-09 ',
  '2020-08-10 ',
  '2020-08-11 ',
  '2020-08-12 ',
  '2020-08-13 ',
  '2020-08-14 ',
  '2020-08-15 ',
  '2020-08-16 ',
  '2020-08-17 ',
  '2020-08-18 ',
  '2020-08-19 ',
  '2020-08-20 ',
  '2020-08-21 ',
  '2020-08-22 ',
  '2020-08-23 ',
  '2020-08-24 ',
  '2020-08-25 ',
  '2020-08-26 ',
  '2020-08-27 ',
  '2020-08-28 ',
  '2020-08-29 ',
  '2020-08-30 ',
  '2020-08-31 ',
  '2020-09-01 ',
  '2020-09-02 ',
  '2020-09-03 ',
  '2020-09-04 ',
  '2020-09-05 ',
  '2020-09-06 ',
  '2020-09-07 ',
  '2020-09-08 ',
  '2020-09-09 ',
  '2020-09-10 ',
  '2020-09-11 ',
  '2020-09-12 ',
  '2020-09-13 ',
  '2020-09-14 ',
  '2020-09-15 ',
  '2020-09-16 ',
  '2020-09-17 ',
  '2020-09-18 ',
  '2020-09-19 ',
  '2020-09-20 ',
  '2020-09-21 ',
  '2020-09-22 ',
  '2020-09-23 ',
  '2020-09-24 ',
  '2020-09-25 ',
  '2020-09-26 ',
  '2020-09-27 ',
  '2020-09-28 ',
  '2020-09-29 ',
  '2020-09-30 ',
  '2020-10-01 ',
  '2020-10-02 ',
  '2020-10-03 ',
  '2020-10-04 ',
  '2020-10-05 ',
  '2020-10-06 ',
  '2020-10-07 ',
  '2020-10-08 ',
  '2020-10-09 ',
  '2020-10-10 ',
  '2020-10-11 ',
  '2020-10-12 ',
  '2020-10-13 ',
  '2020-10-14 ',
  '2020-10-15 ',
  '2020-10-16 ',
  '2020-10-17 ',
  '2020-10-18 ',
  '2020-10-19 ',
  '2020-10-20 ',
  '2020-10-21 ',
  '2020-10-22 ',
  '2020-10-23 ',
  '2020-10-24 ',
  '2020-10-25 ',
  '2020-10-26 ',
  '2020-10-27 ',
  '2020-10-28 '],
 'mipe': ['mxmb',
  'lb',
  'lb',
  'lb',
  'lb',
  'mxmb',
  'memb',
  'memb',
  'lb',
  'mxmb',
  'memb',
  'memb',
  'mxmb',
  'mxmb',
  'lb',
  'mdb',
  'memb',
  'mxmb',
  'lb',
  'memb',
  'mxmb',
  'mxb',
  'mxmb',
  'lb',
  'mxmb',
  'mdb',
  'lb',
  'mxmb',
  'lb',
  'mxmb',
  'mxmb',
  'mxb',
  'mxmb',
  'lb',
  'memb',
  'lb',
  'mxmb',
  'memb',
  'mxmb',
  'lb',
  'memb',
  'mxmb',
  'memb',
  'mxmb',
  'mxmb',
  'memb',
  'mxb',
  'mxmb',
  'mxmb',
  'lb',
  'mdb',
  'mxmb',
  'mxmb',
  'mxmb',
  'lb',
  'mxmb',
  'lb',
  'mxmb',
  'mxmb',
  'mxb',
  'mxmb',
  'lb',
  'mxmb',
  'lb',
  'mxmb',
  'lb',
  'lb',
  'memb',
  'mxmb',
  'mxmb',
  'memb',
  'lb',
  'mxmb',
  'mxb',
  'mxb',
  'mxmb',
  'mxb',
  'mxmb',
  'mxmb',
  'memb',
  'mdb',
  'mxb',
  'mxmb',
  'lb',
  'mxmb',
  'memb',
  'lb',
  'mxmb',
  'memb',
  'mxmb',
  'lb',
  'mxmb',
  'mxmb',
  'mxb',
  'mxmb',
  'mxmb',
  'lb',
  'mdb',
  'lb',
  'memb',
  'mxmb',
  'lb',
  'mxmb',
  'mxmb',
  'mxmb',
  'lb',
  'mxmb',
  'memb',
  'mxmb',
  'memb',
  'mxmb',
  'memb',
  'mxb',
  'mxb',
  'mxb',
  'memb',
  'mxb',
  'mxmb',
  'lb',
  'lb',
  'mdb',
  'lb',
  'mxmb',
  'mxb',
  'mxmb',
  'lb',
  'memb',
  'mdb',
  'lb',
  'mxmb',
  'mxmb',
  'lb',
  'mxmb',
  'lb',
  'mxmb',
  'mxmb',
  'lb',
  'mxmb',
  'lb',
  'mxmb',
  'lb',
  'mxmb',
  'lb',
  'mxmb',
  'mxmb',
  'mxmb',
  'lb',
  'mxmb',
  'mxmb',
  'lb',
  'lb',
  'mdb',
  'mxmb',
  'lb',
  'mxmb',
  'memb',
  'mxmb',
  'lb',
  'memb',
  'mxmb',
  'memb',
  'mxmb',
  'mxmb',
  'mxmb',
  'memb',
  'mxmb',
  'mxmb',
  'mxmb',
  'lb',
  'mxmb',
  'memb',
  'mxb',
  'memb',
  'mxmb',
  'memb',
  'mxmb',
  'mxmb',
  'mxmb',
  'lb',
  'mxmb',
  'mxmb',
  'lb',
  'mdb',
  'mdb',
  'mxmb',
  'mxmb',
  'lb',
  'mdb',
  'mxmb',
  'lb',
  'lb',
  'mxmb',
  'lb',
  'memb',
  'mxmb',
  'lb',
  'mxmb',
  'lb',
  'mxmb',
  'mxmb',
  'lb',
  'mdb',
  'lb',
  'mxmb',
  'memb',
  'memb',
  'mxmb',
  'mxmb',
  'mdb',
  'lb',
  'mxmb',
  'No'],
 'mxne': ['memb',
  'memb',
  'memb',
  'memb',
  'mxb',
  'memb',
  'mxb',
  'lb',
  'mxb',
  'memb',
  'mxb',
  'lb',
  'memb',
  'lb',
  'memb',
  'lb',
  'mxb',
  'memb',
  'mxb',
  'mxb',
  'memb',
  'No',
  'memb',
  'memb',
  'lb',
  'lb',
  'memb',
  'lb',
  'memb',
  'lb',
  'lb',
  'No',
  'memb',
  'memb',
  'mxb',
  'mxb',
  'memb',
  'mxb',
  'memb',
  'memb',
  'mxb',
  'memb',
  'mxb',
  'memb',
  'lb',
  'mxb',
  'No',
  'memb',
  'lb',
  'memb',
  'lb',
  'lb',
  'lb',
  'lb',
  'memb',
  'lb',
  'memb',
  'lb',
  'lb',
  'No',
  'memb',
  'memb',
  'lb',
  'memb',
  'lb',
  'memb',
  'memb',
  'mxb',
  'memb',
  'memb',
  'mxb',
  'mxb',
  'memb',
  'No',
  'No',
  'memb',
  'No',
  'memb',
  'lb',
  'mxb',
  'memb',
  'No',
  'memb',
  'memb',
  'lb',
  'mxb',
  'mxb',
  'memb',
  'mxb',
  'memb',
  'memb',
  'lb',
  'lb',
  'No',
  'memb',
  'lb',
  'memb',
  'lb',
  'memb',
  'mxb',
  'memb',
  'mxb',
  'memb',
  'lb',
  'lb',
  'memb',
  'lb',
  'mxb',
  'memb',
  'mxb',
  'memb',
  'mxb',
  'No',
  'No',
  'No',
  'mxb',
  'No',
  'memb',
  'memb',
  'memb',
  'lb',
  'memb',
  'lb',
  'No',
  'memb',
  'memb',
  'mxb',
  'memb',
  'memb',
  'lb',
  'lb',
  'memb',
  'lb',
  'memb',
  'memb',
  'lb',
  'memb',
  'lb',
  'memb',
  'lb',
  'memb',
  'lb',
  'memb',
  'lb',
  'lb',
  'lb',
  'memb',
  'memb',
  'lb',
  'memb',
  'memb',
  'lb',
  'lb',
  'memb',
  'lb',
  'mxb',
  'lb',
  'memb',
  'mxb',
  'memb',
  'mxb',
  'memb',
  'lb',
  'lb',
  'mxb',
  'memb',
  'lb',
  'lb',
  'memb',
  'memb',
  'mxb',
  'No',
  'mxb',
  'memb',
  'mxb',
  'memb',
  'lb',
  'lb',
  'memb',
  'lb',
  'lb',
  'memb',
  'lb',
  'lb',
  'lb',
  'lb',
  'memb',
  'lb',
  'lb',
  'memb',
  'memb',
  'memb',
  'memb',
  'mxb',
  'memb',
  'memb',
  'lb',
  'memb',
  'lb',
  'lb',
  'memb',
  'lb',
  'memb',
  'lb',
  'mxb',
  'mxb',
  'memb',
  'lb',
  'lb',
  'memb',
  'lb',
  'lmb'],
 'mipv': [28,
  5,
  1,
  14,
  9,
  86,
  4,
  10,
  7,
  197,
  32,
  35,
  352,
  330,
  43,
  307,
  29,
  505,
  111,
  36,
  994,
  20,
  1266,
  209,
  1333,
  1108,
  107,
  1101,
  4,
  1518,
  1483,
  70,
  2190,
  11,
  48,
  113,
  3116,
  114,
  3396,
  229,
  13,
  4115,
  16,
  4922,
  4775,
  105,
  1397,
  6553,
  6474,
  383,
  6621,
  7079,
  7035,
  6118,
  581,
  8462,
  416,
  8999,
  9018,
  6946,
  10617,
  401,
  8322,
  485,
  4817,
  458,
  195,
  220,
  13306,
  14599,
  17,
  395,
  16905,
  211,
  470,
  20538,
  1736,
  22206,
  21065,
  1585,
  22580,
  543,
  27320,
  1443,
  28058,
  935,
  232,
  30560,
  238,
  35265,
  1430,
  35542,
  34202,
  1476,
  39836,
  39743,
  532,
  39197,
  969,
  1319,
  46291,
  91,
  56600,
  55856,
  54244,
  2730,
  55956,
  278,
  55935,
  1090,
  62965,
  522,
  588,
  3236,
  100,
  2771,
  1001,
  96198,
  1723,
  44,
  95689,
  3445,
  99876,
  3519,
  112961,
  1295,
  5485,
  126451,
  2937,
  134606,
  137070,
  435,
  144477,
  7637,
  159067,
  159179,
  375,
  159134,
  2727,
  163401,
  519,
  166676,
  778,
  177415,
  178951,
  174109,
  7989,
  180620,
  175867,
  2149,
  3446,
  179404,
  176486,
  2667,
  179640,
  224,
  191301,
  599,
  1734,
  206682,
  26,
  215265,
  215726,
  213270,
  2737,
  223141,
  226543,
  228335,
  1975,
  236572,
  1904,
  947,
  3618,
  269089,
  6290,
  277500,
  270635,
  256791,
  10780,
  254795,
  236086,
  9377,
  243240,
  237188,
  235302,
  224864,
  4226,
  226761,
  223130,
  5059,
  77,
  235008,
  2818,
  4316,
  235172,
  5958,
  223835,
  6981,
  214933,
  206046,
  1243,
  195842,
  6510,
  188256,
  5958,
  1320,
  203486,
  194682,
  182644,
  3933,
  170333,
  'No'],
 'mxnv': [-26,
  -13,
  -16,
  -3,
  -23,
  -12,
  -48,
  -3,
  -18,
  -37,
  -4,
  -1,
  -72,
  -15,
  -41,
  -46,
  -101,
  -7,
  -57,
  -127,
  -5,
  'No',
  -264,
  -77,
  -252,
  -89,
  -214,
  -63,
  -201,
  -3,
  -122,
  'No',
  -67,
  -66,
  -167,
  -69,
  -111,
  -150,
  -433,
  -130,
  -277,
  -228,
  -368,
  -28,
  -527,
  -188,
  'No',
  -395,
  -244,
  -217,
  -153,
  -211,
  -67,
  -926,
  -434,
  -471,
  -314,
  -363,
  -446,
  'No',
  -1447,
  -1151,
  -1325,
  -1977,
  -956,
  -2277,
  -2107,
  -985,
  -203,
  -230,
  -557,
  -186,
  -196,
  'No',
  'No',
  -75,
  'No',
  -1612,
  -626,
  -1450,
  -994,
  'No',
  -2312,
  -772,
  -916,
  -3781,
  -3741,
  -3593,
  -5075,
  -2273,
  -824,
  -1498,
  -972,
  'No',
  -1383,
  -218,
  -681,
  -1127,
  -635,
  -5889,
  -102,
  -880,
  -278,
  -2556,
  -1133,
  -853,
  -1100,
  -2240,
  -5640,
  -1733,
  -318,
  -1793,
  'No',
  'No',
  'No',
  -2228,
  'No',
  -3292,
  -1947,
  -2342,
  -4133,
  -1916,
  -2242,
  'No',
  -2517,
  -1254,
  -6468,
  -2823,
  -424,
  -1648,
  -95,
  -394,
  -9117,
  -1328,
  -705,
  -5020,
  -4112,
  -5655,
  -4487,
  -1003,
  -3445,
  -2939,
  -2541,
  -841,
  -5588,
  -3778,
  -555,
  -3935,
  -9673,
  -8174,
  -2746,
  -1102,
  -6155,
  -4196,
  -3787,
  -4500,
  -1972,
  -1076,
  -3037,
  -3037,
  -2410,
  -977,
  -3222,
  -3730,
  -1968,
  -2704,
  -1788,
  -169,
  -289,
  -1450,
  -4760,
  'No',
  -3346,
  -462,
  -18,
  -9803,
  -3986,
  -7986,
  -6432,
  -2799,
  -19434,
  -10377,
  -496,
  -2332,
  -7946,
  -3568,
  -6489,
  -6171,
  -1927,
  -3044,
  -1029,
  -5088,
  -1141,
  -1073,
  -14246,
  -6568,
  -5461,
  -2178,
  -11847,
  -1009,
  -7811,
  -8853,
  -4947,
  -8703,
  -8414,
  -5924,
  -6808,
  -5370,
  -3519,
  -6734,
  -5875,
  -7128695],
 'original_val': [150,
  169,
  191,
  230,
  286,
  329,
  394,
  469,
  565,
  635,
  786,
  972,
  1086,
  1198,
  1365,
  1509,
  1767,
  2040,
  2466,
  2854,
  3273,
  3976,
  4370,
  5012,
  5496,
  5938,
  6523,
  7103,
  7739,
  8429,
  9059,
  10021,
  10852,
  11763,
  12845,
  14140,
  15301,
  16776,
  17887,
  19301,
  20970,
  22549,
  24454,
  26417,
  28011,
  30245,
  34257,
  36795,
  39277,
  42309,
  45422,
  48553,
  51833,
  54409,
  57694,
  60706,
  64291,
  67725,
  70896,
  82631,
  86934,
  91862,
  95744,
  100275,
  104064,
  108454,
  113224,
  118657,
  123848,
  129019,
  134653,
  140928,
  146972,
  154235,
  162327,
  169685,
  180324,
  187550,
  194440,
  205181,
  214210,
  228184,
  237259,
  248138,
  258600,
  271689,
  285672,
  295918,
  310147,
  321778,
  335275,
  347840,
  359904,
  379903,
  394320,
  409066,
  424895,
  440210,
  457046,
  476554,
  495962,
  516251,
  536232,
  554430,
  572113,
  593090,
  613736,
  636603,
  654079,
  677662,
  700392,
  724695,
  752284,
  784159,
  817485,
  849999,
  887124,
  918636,
  952990,
  988673,
  1021559,
  1058984,
  1095538,
  1146906,
  1187261,
  1230331,
  1281551,
  1327134,
  1377275,
  1427662,
  1479797,
  1534271,
  1581633,
  1638094,
  1695853,
  1750629,
  1807549,
  1860665,
  1918069,
  1976241,
  2036696,
  2096061,
  2157934,
  2220792,
  2279893,
  2336789,
  2403094,
  2467245,
  2523436,
  2583056,
  2647531,
  2712513,
  2772935,
  2837370,
  2899515,
  2967389,
  3034880,
  3104505,
  3177666,
  3247296,
  3321412,
  3396020,
  3469082,
  3539986,
  3621442,
  3699304,
  3777052,
  3856265,
  3939114,
  4022038,
  4109826,
  4205341,
  4299730,
  4392656,
  4494726,
  4584383,
  4671842,
  4752984,
  4846315,
  4938680,
  5013371,
  5098569,
  5184719,
  5269993,
  5348724,
  5425063,
  5506718,
  5583431,
  5659286,
  5741231,
  5824440,
  5903185,
  5985813,
  6074835,
  6146399,
  6224764,
  6298667,
  6380428,
  6451220,
  6521788,
  6594371,
  6658909,
  6730589,
  6792417,
  6871978,
  6946547,
  7013541,
  7075811,
  7135115,
  7198849,
  7257277,
  0],
 'pprd_val': [122,
  164,
  190,
  216,
  277,
  243,
  390,
  459,
  558,
  438,
  754,
  937,
  734,
  868,
  1322,
  1202,
  1738,
  1535,
  2355,
  2818,
  2279,
  3956,
  3104,
  4803,
  4163,
  4830,
  6416,
  6002,
  7735,
  6911,
  7576,
  9951,
  8662,
  11752,
  12797,
  14027,
  12185,
  16662,
  14491,
  19072,
  20957,
  18434,
  24438,
  21495,
  23236,
  30140,
  32860,
  30242,
  32803,
  41926,
  38801,
  41474,
  44798,
  48291,
  57113,
  52244,
  63875,
  58726,
  61878,
  75685,
  76317,
  91461,
  87422,
  99790,
  99247,
  107996,
  113029,
  118437,
  110542,
  114420,
  134636,
  140533,
  130067,
  154024,
  161857,
  149147,
  178588,
  165344,
  173375,
  203596,
  191630,
  227641,
  209939,
  246695,
  230542,
  270754,
  285440,
  265358,
  309909,
  286513,
  333845,
  312298,
  325702,
  378427,
  354484,
  369323,
  424363,
  401013,
  456077,
  475235,
  449671,
  516160,
  479632,
  498574,
  517869,
  590360,
  557780,
  636325,
  598144,
  676572,
  637427,
  724173,
  751696,
  780923,
  817385,
  847228,
  886123,
  822438,
  951267,
  988629,
  925870,
  1055539,
  995662,
  1143387,
  1074300,
  1229036,
  1276066,
  1200683,
  1374338,
  1293056,
  1342727,
  1533836,
  1437156,
  1630457,
  1536786,
  1591450,
  1807174,
  1701531,
  1915342,
  1812840,
  2036177,
  1929385,
  2157156,
  2043377,
  2100942,
  2162680,
  2395105,
  2286625,
  2347569,
  2580907,
  2644085,
  2533109,
  2596449,
  2834703,
  2719875,
  2967165,
  2843579,
  3103906,
  3175932,
  3040614,
  3321386,
  3180755,
  3253356,
  3326716,
  3618705,
  3476163,
  3550509,
  3627930,
  3937139,
  3785466,
  4107922,
  4204394,
  4296112,
  4123567,
  4488436,
  4306883,
  4401207,
  4496193,
  4835535,
  4683885,
  4777285,
  5089192,
  4941479,
  5032805,
  5113422,
  5200199,
  5502492,
  5356670,
  5436156,
  5736172,
  5824363,
  5668177,
  5982995,
  6070519,
  5911227,
  6218806,
  6074832,
  6373447,
  6236287,
  6315742,
  6593128,
  6463067,
  6724079,
  6604161,
  6866020,
  6945227,
  6810055,
  6881129,
  6952471,
  7194916,
  7086944,
  'No'],
 'nprd_val': [176,
  182,
  207,
  233,
  309,
  341,
  442,
  472,
  583,
  672,
  790,
  973,
  1158,
  1213,
  1406,
  1555,
  1868,
  2047,
  2523,
  2981,
  3278,
  'No',
  4634,
  5089,
  5748,
  6027,
  6737,
  7166,
  7940,
  8432,
  9181,
  'No',
  10919,
  11829,
  13012,
  14209,
  15412,
  16926,
  18320,
  19431,
  21247,
  22777,
  24822,
  26445,
  28538,
  30433,
  'No',
  37190,
  39521,
  42526,
  45575,
  48764,
  51900,
  55335,
  58128,
  61177,
  64605,
  68088,
  71342,
  'No',
  88381,
  93013,
  97069,
  102252,
  105020,
  110731,
  115331,
  119642,
  124051,
  129249,
  135210,
  141114,
  147168,
  'No',
  'No',
  169760,
  'No',
  189162,
  195066,
  206631,
  215204,
  'No',
  239571,
  248910,
  259516,
  275470,
  289413,
  299511,
  315222,
  324051,
  336099,
  349338,
  360876,
  'No',
  395703,
  409284,
  425576,
  441337,
  457681,
  482443,
  496064,
  517131,
  536510,
  556986,
  573246,
  593943,
  614836,
  638843,
  659719,
  679395,
  700710,
  726488,
  'No',
  'No',
  'No',
  852227,
  'No',
  921928,
  954937,
  991015,
  1025692,
  1060900,
  1097780,
  'No',
  1189778,
  1231585,
  1288019,
  1329957,
  1377699,
  1429310,
  1479892,
  1534665,
  1590750,
  1639422,
  1696558,
  1755649,
  1811661,
  1866320,
  1922556,
  1977244,
  2040141,
  2099000,
  2160475,
  2221633,
  2285481,
  2340567,
  2403649,
  2471180,
  2533109,
  2591230,
  2650277,
  2713615,
  2779090,
  2841566,
  2903302,
  2971889,
  3036852,
  3105581,
  3180703,
  3250333,
  3323822,
  3396997,
  3472304,
  3543716,
  3623410,
  3702008,
  3778840,
  3856434,
  3939403,
  4023488,
  4114586,
  'No',
  4303076,
  4393118,
  4494744,
  4594186,
  4675828,
  4760970,
  4852747,
  4941479,
  5032805,
  5108946,
  5185215,
  5272325,
  5356670,
  5428631,
  5513207,
  5589602,
  5661213,
  5744275,
  5825469,
  5908273,
  5986954,
  6075908,
  6160645,
  6231332,
  6304128,
  6382606,
  6463067,
  6522797,
  6602182,
  6667762,
  6735536,
  6801120,
  6880392,
  6952471,
  7020349,
  7081181,
  7138634,
  7205583,
  7263152,
  7128695]}

In [33]:
err_df=pd.DataFrame(err_dict)
err_df

            date  mipe  mxne    mipv      mxnv  original_val pprd_val nprd_val
0    2020-03-31   mxmb  memb      28       -26           150      122      176
1    2020-04-01     lb  memb       5       -13           169      164      182
2    2020-04-02     lb  memb       1       -16           191      190      207
3    2020-04-03     lb  memb      14        -3           230      216      233
4    2020-04-04     lb   mxb       9       -23           286      277      309
..           ...   ...   ...     ...       ...           ...      ...      ...
207  2020-10-24   mxmb    lb  194682     -5370       7075811  6881129  7081181
208  2020-10-25    mdb    lb  182644     -3519       7135115  6952471  7138634
209  2020-10-26     lb  memb    3933     -6734       7198849  7194916  7205583
210  2020-10-27   mxmb    lb  170333     -5875       7257277  7086944  7263152
211  2020-10-28     No   lmb      No  -7128695             0       No  7128695

[212 rows x 8 columns]

In [34]:
err_df.to_excel("trerr_df.xlsx")
errdf=pd.read_excel(r"C:\Users\Mark 1\trerr_df.xlsx")
errdf = errdf.loc[:, ~errdf.columns.str.contains('^Unnamed')]
errdf.to_excel("trerr_df.xlsx")

In [35]:
Counter(err_df['mipe'])

Counter({'mxmb': 95, 'lb': 56, 'memb': 32, 'mdb': 13, 'mxb': 15, 'No': 1})

In [36]:
mnval=max(list(Counter(err_df['mipe']).values()))
mnvalidx=list(Counter(err_df['mipe']).values()).index(mnval)
mnkys=list(Counter(err_df['mipe']).keys())[mnvalidx]
print("method: "+mnkys+" and values is: ",Counter(err_df['mipe'])[mnkys])

method: mxmb and values is:  95

In [37]:
Counter(err_df['mxne'])

Counter({'memb': 91, 'mxb': 37, 'lb': 68, 'No': 15, 'lmb': 1})

In [38]:
mxval=max(list(Counter(err_df['mxne']).values()))
mxvalidx=list(Counter(err_df['mxne']).values()).index(mxval)
mxkys=list(Counter(err_df['mxne']).keys())[mxvalidx]
print("method: "+mxkys+" and values is: ",Counter(err_df['mxne'])[mxkys])

method: memb and values is:  91

In [39]:
err_df['mipe'][len(err_df)-2]

'mxmb'

In [40]:
err_df['mxne'][len(err_df)-2]

'lb'